[unix_http_server]
file=/run/bento-supervisor.sock
chmod=0600

[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/run/bento-supervisord.pid
childlogdir=/tmp
minfds=1024
minprocs=200
strip_ansi=true

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///run/bento-supervisor.sock

[include]
files=/etc/bento/programs/*.conf
