# bento-managed: true
[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log

[program:system-logrotate]
command=/usr/sbin/logrotate -v /etc/logrotate.conf
autostart=false
autorestart=false
user=root
