# bento-managed: true
# app vb1
server {
  listen 80;
  listen [::]:80;
  server_name keke.com;

  
  
  root /home/vb1/code/public;
  include /etc/nginx/snippets/app-common.conf;

  

  

  
  location / {
    try_files $uri $uri/ /index.php?$query_string;
  }
  location ~ \.php$ {
    if ($uri !~ ^/index\.php$) { return 404; }
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_pass unix:/run/php-fpm/php85/vb1.sock;
  }
  
  
  
}

server {
  listen 443 ssl;
  listen [::]:443 ssl;
  http2 on;
  server_name keke.com;

  include /etc/nginx/snippets/boot-ssl.conf;
  add_header Alt-Svc 'h3=":443"; ma=86400' always;

  root /home/vb1/code/public;
  include /etc/nginx/snippets/app-common.conf;

  

  

  
  location / {
    try_files $uri $uri/ /index.php?$query_string;
  }
  location ~ \.php$ {
    if ($uri !~ ^/index\.php$) { return 404; }
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_pass unix:/run/php-fpm/php85/vb1.sock;
  }
  
  
}
