# bento-managed: true
name: bento
networks:
  private:
    driver: bridge
    name: bento_private
services:
  nginx:
    image: "bento/nginx:latest"
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    network_mode: host
    restart: unless-stopped
    volumes:
      - "./generated/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./generated/nginx/sites:/etc/nginx/sites:ro"
      - "./generated/nginx/snippets:/etc/nginx/snippets:ro"
      - "./certs:/etc/nginx/certs"
      - "./homes:/home:ro"
      - "./runtime/php-fpm:/run/php-fpm:ro"
      - "./logs/nginx:/var/log/nginx"
  redis:
    image: "redis:7-alpine"
    restart: unless-stopped
    networks:
      - private
    command:
      - redis-server
      - "--appendonly"
      - "yes"
      - "--protected-mode"
      - "yes"
    volumes:
      - "bento-redis-data:/data"
volumes:
  bento-redis-data: null
