try_files $fastcgi_script_name =404;

include fastcgi_params;

fastcgi_index index.php;
fastcgi_buffers 8 16k;
fastcgi_buffer_size 32k;
fastcgi_read_timeout 60s;

limit_req zone=req_per_ip burst=40 nodelay;
limit_conn conn_per_ip 20;

fastcgi_param HTTP_PROXY "";
fastcgi_param DOCUMENT_ROOT $realpath_root;
fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
fastcgi_param PHP_ADMIN_VALUE "open_basedir=$base/:/home/$site_user/:/tmp/:/usr/local/lib/php/:/var/log/php/";
