from __future__ import annotations

import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

import vibeops.services.cron_runtime as cron_runtime
from vibeops.utils.validation import validate_cron_workdir
from vibeops.commands.cron_commands import cron_render_values, validate_schedule
from vibeops.utils.errors import StackError


class CronValidationTests(unittest.TestCase):
    def test_valid_schedule(self) -> None:
        self.assertEqual(validate_schedule("*/5 * * * *"), "*/5 * * * *")
        self.assertEqual(validate_schedule("@hourly"), "@hourly")

    def test_schedule_rejects_shell_syntax(self) -> None:
        with self.assertRaises(StackError):
            validate_schedule("* * * * *; touch /tmp/bad")

    def test_workdir_is_app_bounded(self) -> None:
        self.assertEqual(validate_cron_workdir("shop", "/home/shop/www"), "/home/shop/www")
        for path in ("/tmp", "/home/other/www", "/home/shop/www/../private"):
            with self.subTest(path=path), self.assertRaises(StackError):
                validate_cron_workdir("shop", path)

    def test_render_values_include_runtime_policy(self) -> None:
        values = cron_render_values({
            "app": "shop",
            "job_name": "schedule",
            "php_version": "8.5",
            "schedule": "* * * * *",
            "command": "php artisan schedule:run",
            "workdir": "/home/shop/www",
            "output": "file",
            "timeout": 50,
            "lock": "artisan",
            "timezone": "UTC",
        })
        self.assertEqual(values["PHP_SERVICE"], "php85-runner")
        self.assertEqual(values["OUTPUT"], "file")
        self.assertEqual(values["TIMEOUT"], 50)
        self.assertEqual(values["QUOTED_LOCK"], "artisan")


class CronRenderTests(unittest.TestCase):
    def test_empty_crontab_has_root_maintenance_only(self) -> None:
        with tempfile.TemporaryDirectory() as tmp, patch.object(cron_runtime, "CRON_RUNTIME_DIR", Path(tmp)):
            system = cron_runtime.rebuild_supercronic_crontab("8.5")
            content = system.read_text()
            self.assertNotIn("/bin/true", content)
            self.assertIn("/usr/sbin/logrotate", content)
            self.assertEqual(list((system.parent / "apps").glob("*.cron")), [])
            rotation = system.parent / ".logrotate.conf"
            rotation_content = rotation.read_text()
            self.assertIn("cron-php85-runner-*.log", rotation_content)
            self.assertIn("fpm-php-8.5.error.log", rotation_content)
            self.assertIn("dateext", rotation_content)
            self.assertIn("dateformat -%Y-%m-%d", rotation_content)

    def test_jobs_are_merged_into_an_app_owned_crontab(self) -> None:
        with tempfile.TemporaryDirectory() as tmp, patch.object(cron_runtime, "CRON_RUNTIME_DIR", Path(tmp)):
            jobs = cron_runtime.cron_jobs_dir_for("8.5")
            jobs.mkdir(parents=True)
            (jobs / "shop-schedule.cron").write_text(
                "# Generated by manage.py\n# App: shop\n# Job: schedule\n* * * * * /bin/echo ok\n"
            )
            system = cron_runtime.rebuild_supercronic_crontab("8.5")
            app_content = (system.parent / "apps" / "shop.cron").read_text()
            self.assertIn("/bin/echo ok", app_content)
            self.assertNotIn("/bin/echo ok", system.read_text())
            self.assertNotIn("/bin/true", app_content)


if __name__ == "__main__":
    unittest.main()
