load_module modules/ngx_http_acme_module.so;

pcre_jit on;
user nginx;

worker_processes auto;
worker_rlimit_nofile 65535;

pid /var/run/nginx.pid;
timer_resolution 10ms;

events {
    multi_accept on;
    worker_connections 65535;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    include /etc/nginx/conf.d/*.conf;
}
