#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

if [[ -f .env ]]; then
  set -a
  # shellcheck disable=SC1091
  source .env
  set +a
fi

usage() {
  cat >&2 <<'USAGE'
Usage: ./scripts/create-cron.sh <username> <domain> <job-name> [--php 8.4] -- '<schedule>' '<command>'

Creates a supercronic job for a PHP app. The command runs inside the selected
PHP container as the same Linux user as PHP-FPM and with the app workdir.

Examples:
  ./scripts/create-cron.sh myuser example.com schedule --php 8.4 -- '* * * * *' 'php artisan schedule:run'
  ./scripts/create-cron.sh myuser example.com queue --php 8.4 -- '*/5 * * * *' 'php artisan queue:work --stop-when-empty'
USAGE
}

php_service_for() {
  local version="$1"
  printf 'php%s' "${version//./}"
}

shell_quote() {
  local value="$1"
  printf '%q' "$value"
}

USERNAME=""
DOMAIN=""
JOB_NAME=""
PHP_VERSION="${DEFAULT_PHP_VERSION:-8.4}"
WORKDIR=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --php|--php-version)
      PHP_VERSION="${2:-}"
      shift 2
      ;;
    --workdir|-w)
      WORKDIR="${2:-}"
      shift 2
      ;;
    --)
      shift
      break
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      if [[ -z "$USERNAME" ]]; then
        USERNAME="$1"
      elif [[ -z "$DOMAIN" ]]; then
        DOMAIN="$1"
      elif [[ -z "$JOB_NAME" ]]; then
        JOB_NAME="$1"
      else
        echo "Unknown argument before --: $1" >&2
        usage
        exit 1
      fi
      shift
      ;;
  esac
done

[[ -n "$USERNAME" && -n "$DOMAIN" && -n "$JOB_NAME" ]] || { usage; exit 1; }
[[ $# -eq 2 ]] || { usage; exit 1; }
SCHEDULE="$1"
COMMAND="$2"

[[ "$USERNAME" =~ ^[a-z_][a-z0-9_-]{0,31}$ ]] || { echo "Invalid username: $USERNAME" >&2; exit 1; }
[[ "$DOMAIN" =~ ^[A-Za-z0-9._-]+$ ]] || { echo "Invalid domain/path name: $DOMAIN" >&2; exit 1; }
[[ "$JOB_NAME" =~ ^[A-Za-z0-9_.-]+$ ]] || { echo "Invalid job-name: $JOB_NAME" >&2; exit 1; }
[[ "$PHP_VERSION" =~ ^[0-9]+\.[0-9]+$ ]] || { echo "Invalid PHP version: $PHP_VERSION" >&2; exit 1; }
[[ -n "$SCHEDULE" && -n "$COMMAND" ]] || { usage; exit 1; }

PHP_SERVICE="$(php_service_for "$PHP_VERSION")"
APP_HOME="/home/$USERNAME"
if [[ -z "$WORKDIR" ]]; then
  WORKDIR="$APP_HOME/$DOMAIN"
fi

if [[ ! -f "php/$PHP_VERSION/users.d/$USERNAME.env" ]]; then
  echo "PHP $PHP_VERSION user $USERNAME does not exist; creating it first."
  ./scripts/create-user.sh "$USERNAME" --php "$PHP_VERSION"
fi

mkdir -p "php/$PHP_VERSION/cron.d" "home/$USERNAME/$DOMAIN"

safe_domain="$(printf '%s' "$DOMAIN" | tr -c 'A-Za-z0-9_.-' '_')"
CRON_PATH="php/$PHP_VERSION/cron.d/$USERNAME-$safe_domain-$JOB_NAME.cron"

quoted_user="$(shell_quote "$USERNAME")"
quoted_workdir="$(shell_quote "$WORKDIR")"
quoted_command="$(shell_quote "$COMMAND")"

cat > "$CRON_PATH" <<EOF
# Generated by scripts/create-cron.sh
# App: $USERNAME $DOMAIN
# PHP: $PHP_VERSION ($PHP_SERVICE)
$SCHEDULE /usr/local/bin/php-cron-as $quoted_user $quoted_workdir sh -lc $quoted_command
EOF

chmod 0644 "$CRON_PATH" || true

echo "Created cron job: docker-stack/$CRON_PATH"
echo "Runs as: $USERNAME"
echo "Workdir: $WORKDIR"
echo "Command: $COMMAND"

if command -v docker >/dev/null 2>&1 && docker compose ps --services --filter status=running 2>/dev/null | grep -qx "$PHP_SERVICE"; then
  docker compose exec -T "$PHP_SERVICE" php-user-sync "$USERNAME"
  docker compose exec -T "$PHP_SERVICE" sh -lc 'if command -v s6-svc >/dev/null 2>&1 && [ -e /run/service/cron ]; then s6-svc -t /run/service/cron; fi' || true
  echo "Asked $PHP_SERVICE cron service to reload. If the job does not appear, restart it: docker compose restart $PHP_SERVICE"
else
  echo "$PHP_SERVICE is not running; start/restart it to load this cron job."
fi
