#!/usr/bin/env python3
"""Pure-Python management CLI for VibeOps.

VibeOps is a vibe-coding ops stack. No third-party dependencies are required.
The CLI keeps lightweight metadata in runtime/state/stack.json while generating
disposable runtime config consumed by Docker, PHP-FPM, supercronic, and nginx.
"""
from __future__ import annotations

import argparse
import datetime as _dt
import json
import os
import re
import secrets
import shlex
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any, Iterable

ROOT = Path(__file__).resolve().parents[1]
CONFIG_DIR = ROOT / "config"
RUNTIME_DIR = ROOT / "runtime"
STATE_DIR = RUNTIME_DIR / "state"
DB_PATH = STATE_DIR / "stack.json"
LEGACY_DB_PATH = ROOT / "stack.json"
GENERATED_DIR = RUNTIME_DIR / "generated"
CUSTOM_DIR = RUNTIME_DIR / "custom"
HOME_DIR = RUNTIME_DIR / "home"
PHP_CONFIG_DIR = CONFIG_DIR / "php"
PHP_GENERATED_DIR = GENERATED_DIR / "php"
PHP_VERSIONS_DIR = PHP_GENERATED_DIR / "versions"
LEGACY_PHP_VERSIONS_DIR = PHP_CONFIG_DIR / "versions"
PHP_TEMPLATE_DIR = PHP_CONFIG_DIR / "templates"
MYSQL_TEMPLATE_DIR = CONFIG_DIR / "mysql" / "templates"
NGINX_TEMPLATE_DIR = CONFIG_DIR / "nginx" / "templates"
NGINX_VHOST_DIR = GENERATED_DIR / "nginx" / "vhosts"
CERTS_DIR = RUNTIME_DIR / "certs"
PHP_SOCKET_DIR = RUNTIME_DIR / "run" / "php-fpm"
PHP_LOG_DIR = RUNTIME_DIR / "logs" / "php"
CRON_RUNTIME_DIR = GENERATED_DIR / "cron"
SCHEMA_VERSION = 3
DOCROOT_NAME = "www"
GENERATED_HEADER = "# GENERATED BY VIBEOPS. Do not edit directly; update runtime/state/stack.json and run ./manage.py render.\n"

APP_NAME_RE = re.compile(r"^[a-z_][a-z0-9_-]{0,31}$")
USERNAME_RE = APP_NAME_RE
DOMAIN_RE = re.compile(r"^[A-Za-z0-9.-]+$")
DOMAIN_PATH_RE = re.compile(r"^[A-Za-z0-9._-]+$")
PHP_VERSION_RE = re.compile(r"^[0-9]+\.[0-9]+$")
DB_NAME_RE = re.compile(r"^[A-Za-z0-9_]+$")
PUBLIC_DIR_RE = re.compile(r"^[A-Za-z0-9._/-]*$")
MYSQL_SERVICE_RE = re.compile(r"^mysql[0-9]+$")
JOB_RE = re.compile(r"^[A-Za-z0-9_.-]+$")


class StackError(RuntimeError):
    pass


def now() -> str:
    return _dt.datetime.now(_dt.timezone.utc).replace(microsecond=0).isoformat()


def rel(path: Path | str) -> str:
    p = Path(path)
    try:
        return str(p.resolve().relative_to(ROOT))
    except Exception:
        return str(p)


def info(message: str) -> None:
    print(message)


def warn(message: str) -> None:
    print(f"Warning: {message}", file=sys.stderr)


def die(message: str) -> None:
    raise StackError(message)


def validate(value: str, pattern: re.Pattern[str], label: str) -> str:
    if not value or not pattern.match(value):
        die(f"Invalid {label}: {value}")
    return value


def parse_env_file(path: Path) -> dict[str, str]:
    env: dict[str, str] = {}
    if not path.exists():
        return env
    for raw in path.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key:
            env[key] = value
    return env


def stack_env() -> dict[str, str]:
    env = parse_env_file(ROOT / ".env")
    merged = dict(env)
    merged.update(os.environ)
    return merged


def default_php_version() -> str:
    return stack_env().get("DEFAULT_PHP_VERSION", "8.4")


def default_mysql_service() -> str:
    return stack_env().get("DEFAULT_MYSQL_SERVICE", "mysql84")


def mysql_root_password(env: dict[str, str], service: str) -> str | None:
    return env.get(f"{service.upper()}_ROOT_PASSWORD") or env.get("MYSQL_ROOT_PASSWORD")


def php_service_for(version: str) -> str:
    return "php" + version.replace(".", "")


def php_cron_service_for(version: str) -> str:
    return php_service_for(version) + "-cron"


def php_cli_service_for(version: str) -> str:
    return php_service_for(version) + "-cli"


def php_version_config_dir(version: str) -> Path:
    return PHP_VERSIONS_DIR / version


def cron_dir_for(version: str) -> Path:
    return CRON_RUNTIME_DIR / php_service_for(version)


def cron_jobs_dir_for(version: str) -> Path:
    return cron_dir_for(version) / "jobs"


def empty_db() -> dict[str, Any]:
    return {
        "schema": SCHEMA_VERSION,
        "defaults": {
            "php_version": default_php_version(),
            "mysql_service": default_mysql_service(),
        },
        "apps": {},
        "domains": {},
        "sites": {},
        "users": {},
        "crons": {},
        "updated_at": now(),
    }


def state_path() -> Path:
    if DB_PATH.exists():
        return DB_PATH
    if LEGACY_DB_PATH.exists():
        warn(f"using legacy state at {rel(LEGACY_DB_PATH)}; run './manage.py state migrate' to move it to {rel(DB_PATH)}")
        return LEGACY_DB_PATH
    return DB_PATH


def normalize_db(data: dict[str, Any]) -> dict[str, Any]:
    schema = int(data.get("schema", 0) or 0)
    if schema > SCHEMA_VERSION:
        die(f"state schema is {schema}; this CLI expects schema {SCHEMA_VERSION}")
    data["schema"] = SCHEMA_VERSION
    data.setdefault("defaults", {})
    data["defaults"].setdefault("php_version", default_php_version())
    data["defaults"].setdefault("mysql_service", default_mysql_service())
    data.setdefault("apps", {})
    data.setdefault("domains", {})
    data.setdefault("sites", {})
    data.setdefault("users", {})
    data.setdefault("crons", {})
    for app_name, app in data.get("apps", {}).items():
        if isinstance(app, dict):
            app.setdefault("name", app_name)
            if app.get("vhost"):
                app["vhost"] = rel(app_vhost_path(app_name))
    for domain, site in data.get("sites", {}).items():
        if isinstance(site, dict) and site.get("type") == "proxy":
            site.setdefault("domain", domain)
            site["vhost"] = rel(NGINX_VHOST_DIR / f"{domain}.conf")
    return data


def load_db() -> dict[str, Any]:
    path = state_path()
    if not path.exists():
        return empty_db()
    try:
        data = json.loads(path.read_text())
    except json.JSONDecodeError as exc:
        die(f"Cannot parse {rel(path)}: {exc}")
    if not isinstance(data, dict):
        die(f"{rel(path)} must contain a JSON object")
    return normalize_db(data)


def save_db(data: dict[str, Any]) -> None:
    normalize_db(data)
    data["schema"] = SCHEMA_VERSION
    data["updated_at"] = now()
    text = json.dumps(data, indent=2, sort_keys=True) + "\n"
    mkdir(DB_PATH.parent)
    fd, tmp_name = tempfile.mkstemp(prefix=".stack.", suffix=".json", dir=str(DB_PATH.parent))
    try:
        with os.fdopen(fd, "w") as fh:
            fh.write(text)
        os.replace(tmp_name, DB_PATH)
    finally:
        if os.path.exists(tmp_name):
            os.unlink(tmp_name)


def upsert_timestamp(item: dict[str, Any]) -> None:
    item.setdefault("created_at", now())
    item["updated_at"] = now()


def mkdir(path: Path, mode: int | None = None) -> None:
    path.mkdir(parents=True, exist_ok=True)
    if mode is not None:
        try:
            path.chmod(mode)
        except PermissionError:
            warn(f"could not chmod {rel(path)}")


def write_text(path: Path, content: str, mode: int | None = None) -> None:
    mkdir(path.parent)
    path.write_text(content)
    if mode is not None:
        try:
            path.chmod(mode)
        except PermissionError:
            warn(f"could not chmod {rel(path)}")


def render_template_text(text: str, values: dict[str, Any]) -> str:
    for key, value in values.items():
        text = text.replace(f"__{key}__", str(value))
    return text


def template_text(path: Path, values: dict[str, Any]) -> str:
    if not path.exists():
        die(f"Missing template: vibeops/{rel(path)}")
    return render_template_text(path.read_text(), values)


def write_template(path: Path, template: Path, values: dict[str, Any], mode: int | None = None, *, generated: bool = False) -> None:
    content = template_text(template, values)
    if generated:
        content = GENERATED_HEADER + content
    write_text(path, content, mode)


def mysql_string_literal(value: str) -> str:
    return value.replace("\\", "\\\\").replace("'", "''")


def command_exists(name: str) -> bool:
    return shutil.which(name) is not None


def run(cmd: list[str], *, input_text: str | None = None, check: bool = True, capture: bool = False) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        cmd,
        cwd=str(ROOT),
        input=input_text,
        text=True,
        check=check,
        stdout=subprocess.PIPE if capture else None,
        stderr=subprocess.PIPE if capture else None,
    )


def docker_available() -> bool:
    return command_exists("docker")


def running_services() -> set[str]:
    if not docker_available():
        return set()
    cp = run(
        ["docker", "compose", "ps", "--services", "--filter", "status=running"],
        check=False,
        capture=True,
    )
    if cp.returncode != 0:
        return set()
    return {line.strip() for line in cp.stdout.splitlines() if line.strip()}


def service_running(service: str) -> bool:
    return service in running_services()


def nginx_reload(no_reload: bool = False) -> None:
    if no_reload:
        return
    if service_running("nginx"):
        run(["docker", "compose", "exec", "-T", "nginx", "nginx", "-t"])
        run(["docker", "compose", "exec", "-T", "nginx", "nginx", "-s", "reload"])
        info("Reloaded nginx")
    else:
        info("nginx container is not running; start it then run: docker compose exec nginx nginx -t && docker compose exec nginx nginx -s reload")


def php_disable_default_pool(service: str) -> None:
    # Official PHP images ship [www] fragments in more than one file (for
    # example www.conf and sometimes docker.conf). VibeOps uses only generated
    # per-user pools, so disable any default [www] fragments at runtime too.
    run([
        "docker", "compose", "exec", "-T", service, "sh", "-lc",
        "for f in /usr/local/etc/php-fpm.d/*.conf; do "
        "[ -e \"$f\" ] || continue; "
        "if grep -q '^\\[www\\]' \"$f\"; then mv \"$f\" \"$f.disabled\"; fi; "
        "done; "
        "rm -f /usr/local/etc/php-fpm.d/zz-pools.conf; "
        "printf '[global]\\nerror_log = /proc/self/fd/2\\nprocess.max = 32\\ninclude=/usr/local/etc/php-fpm.d/pools/*.conf\\n' > /usr/local/etc/php-fpm.d/zz-vibeops.conf; ",
    ], check=False)


def php_reload(service: str, username: str, no_reload: bool = False) -> None:
    if service_running(service):
        php_disable_default_pool(service)
        run(["docker", "compose", "exec", "-T", service, "php-user-sync", username])
        if not no_reload:
            run(["docker", "compose", "exec", "-T", service, "php-fpm", "-tt"])
            run([
                "docker", "compose", "exec", "-T", service, "sh", "-lc",
                "kill -USR2 1",
            ])
            info(f"Reloaded {service}")
    else:
        info(f"{service} is not running; run/restart it to create the Linux user inside that PHP container.")


def rebuild_supercronic_crontab(php_version: str) -> Path:
    cron_dir = cron_dir_for(php_version)
    mkdir(cron_dir)
    combined = cron_dir / ".supercronic.cron"
    lines = [
        "SHELL=/bin/sh",
        "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
        "",
    ]
    for cron_file in sorted(cron_jobs_dir_for(php_version).glob("*.cron")):
        lines.append(f"# /usr/local/etc/php/cron.d/{cron_file.name}")
        lines.append(cron_file.read_text().rstrip("\n"))
        lines.append("")
    write_text(combined, "\n".join(lines) + "\n", 0o644)
    return combined


def cron_reload(service: str, usernames: Iterable[str] = ()) -> None:
    if service_running(service):
        script = r'''
set -eu
php-user-sync "$@"
cmdline="$(tr '\000' ' ' < /proc/1/cmdline || true)"
case "$cmdline" in
  *supercronic*) kill -USR2 1 ;;
  *) echo "Supercronic is not running as PID 1 ($cmdline)" >&2; exit 42 ;;
esac
'''
        cp = run(["docker", "compose", "exec", "-T", service, "sh", "-lc", script, "--", *usernames], check=False)
        if cp.returncode == 0:
            info(f"Reloaded {service} cron with SIGUSR2")
        elif cp.returncode == 42:
            run(["docker", "compose", "restart", service])
            info(f"Restarted idle {service} to start Supercronic")
        else:
            die(f"Failed to reload {service} cron (exit {cp.returncode})")
    else:
        info(f"{service} is not running; start it to load this cron job.")


def read_uid_from_env(path: Path) -> int | None:
    try:
        for line in path.read_text().splitlines():
            if line.startswith("UID="):
                return int(line.split("=", 1)[1])
    except Exception:
        return None
    return None


def allocate_uid(app_name: str, explicit_uid: int | None, db: dict[str, Any]) -> int:
    if explicit_uid is not None:
        return explicit_uid

    existing = db.get("apps", {}).get(app_name, {}).get("uid")
    if isinstance(existing, int):
        return existing

    for base in (PHP_VERSIONS_DIR, LEGACY_PHP_VERSIONS_DIR):
        for path in sorted(base.glob(f"*/users.d/{app_name}.env")):
            uid = read_uid_from_env(path)
            if uid is not None:
                return uid

    max_uid = 0
    for app in db.get("apps", {}).values():
        uid = app.get("uid") if isinstance(app, dict) else None
        if isinstance(uid, int):
            max_uid = max(max_uid, uid)
    for base in (PHP_VERSIONS_DIR, LEGACY_PHP_VERSIONS_DIR):
        for path in base.glob("*/users.d/*.env"):
            uid = read_uid_from_env(path)
            if uid is not None:
                max_uid = max(max_uid, uid)
    return 10000 if max_uid < 10000 else max_uid + 1


def generate_password(length: int = 20) -> str:
    alphabet = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
    return "".join(secrets.choice(alphabet) for _ in range(length))


def create_mysql_user(username: str, password: str | None, mysql_service: str) -> tuple[bool, str | None]:
    env = stack_env()
    mysql_service = validate(mysql_service, MYSQL_SERVICE_RE, "MySQL service")
    if not (ROOT / ".env").exists() or not service_running(mysql_service):
        info(f"Skipped MySQL user creation; start {mysql_service} and rerun, or pass --no-mysql.")
        return False, None
    root_password = mysql_root_password(env, mysql_service)
    if not root_password:
        info(f"Skipped MySQL user creation; {mysql_service.upper()}_ROOT_PASSWORD or MYSQL_ROOT_PASSWORD is missing.")
        return False, None

    cred_dir = HOME_DIR / username / ".credentials"
    cred_path = cred_dir / f"{mysql_service}.env"
    existing_password = parse_env_file(cred_path).get("MYSQL_PASSWORD") if cred_path.exists() else None
    password = password or env.get(f"{mysql_service.upper()}_USER_PASSWORD") or env.get("MYSQL_USER_PASSWORD") or existing_password or generate_password()
    mkdir(cred_dir, 0o700)
    write_template(cred_path, MYSQL_TEMPLATE_DIR / "user-credentials.env.template", {
        "USERNAME": username,
        "MYSQL_SERVICE": mysql_service,
        "MYSQL_PASSWORD": password,
    }, 0o600)

    sql = template_text(MYSQL_TEMPLATE_DIR / "create-user.sql.template", {
        "USERNAME": username,
        "MYSQL_PASSWORD_SQL": mysql_string_literal(password),
    })
    run(["docker", "compose", "exec", "-T", mysql_service, "mysql", "-uroot", f"-p{root_password}"], input_text=sql)
    info(f"MySQL account on {mysql_service}: {username} / {password}")
    info(f"Saved: vibeops/{rel(cred_path)}")
    return True, rel(cred_path)



def app_home(app_name: str) -> Path:
    return HOME_DIR / app_name


def app_www(app_name: str) -> Path:
    return app_home(app_name) / DOCROOT_NAME


def validate_public_dir(public_dir: str | None) -> str:
    public_dir = (public_dir or "").strip().strip("/")
    if public_dir in {".", ".."} or public_dir.startswith("../") or "/../" in public_dir or public_dir.endswith("/.."):
        die(f"Invalid public_dir: {public_dir}")
    if not PUBLIC_DIR_RE.match(public_dir):
        die(f"Invalid public_dir: {public_dir}")
    return public_dir


def app_document_root(app_name: str, public_dir: str | None = "") -> Path:
    public_dir = validate_public_dir(public_dir)
    return app_www(app_name) / public_dir if public_dir else app_www(app_name)


def container_document_root(app_name: str, public_dir: str | None = "") -> str:
    public_dir = validate_public_dir(public_dir)
    base = f"/home/{app_name}/{DOCROOT_NAME}"
    return f"{base}/{public_dir}" if public_dir else base


def app_vhost_path(app_name: str) -> Path:
    return NGINX_VHOST_DIR / f"app-{app_name}.conf"


def render_template(template: Path, destination: Path, values: dict[str, Any]) -> None:
    write_template(destination, template, values, generated=True)


def normalize_aliases(alias: Iterable[str] | None, aliases: str | None) -> list[str]:
    out: list[str] = []
    for value in alias or []:
        for item in value.split(","):
            item = item.strip()
            if item:
                out.append(validate(item, DOMAIN_RE, "alias domain"))
    if aliases:
        for item in aliases.split(","):
            item = item.strip()
            if item:
                out.append(validate(item, DOMAIN_RE, "alias domain"))
    return sorted(dict.fromkeys(out))


def domains_for(main_domain: str, aliases: Iterable[str]) -> list[str]:
    ordered = [main_domain, *aliases]
    return list(dict.fromkeys(ordered))


def assert_domain_free(domain: str, db: dict[str, Any], *, allow_app: str | None = None, allow_domain: str | None = None) -> None:
    owner = db.get("domains", {}).get(domain)
    if not owner:
        return
    if owner.get("kind") == "php" and allow_app and owner.get("app") == allow_app:
        return
    if owner.get("kind") == "proxy" and allow_domain and owner.get("domain") == allow_domain:
        return
    die(f"Domain already exists in stack.json: {domain} ({owner.get('kind')})")


def apply_app_mysql_metadata(app: dict[str, Any], app_name: str, mysql_service: str, credential_path: str | None = None) -> None:
    app["mysql_service"] = mysql_service
    app["mysql_host"] = mysql_service
    app["mysql_port"] = 3306
    app["mysql_user_name"] = app_name
    if credential_path:
        app["mysql_credentials"] = credential_path


def create_database(app_name: str, suffix: str, mysql_service: str) -> str | None:
    mysql_service = validate(mysql_service, MYSQL_SERVICE_RE, "MySQL service")
    validate(suffix, DB_NAME_RE, "database suffix")
    db_full_name = f"{app_name}_{suffix}"
    env = stack_env()
    root_password = mysql_root_password(env, mysql_service)
    if (ROOT / ".env").exists() and service_running(mysql_service) and root_password:
        sql = template_text(MYSQL_TEMPLATE_DIR / "create-database.sql.template", {
            "DB_FULL_NAME": db_full_name,
            "USERNAME": app_name,
        })
        run(["docker", "compose", "exec", "-T", mysql_service, "mysql", "-uroot", f"-p{root_password}"], input_text=sql)
        info(f"MySQL database on {mysql_service}: {db_full_name}")
    else:
        info(f"Skipped database creation; {mysql_service} is not running, .env is missing, or root password is unset.")
    return db_full_name


def ensure_app_identity(app_name: str, php_version: str, db: dict[str, Any], *, uid: int | None = None, no_mysql: bool = False, mysql_password: str | None = None, mysql_service: str | None = None, no_reload: bool = False) -> dict[str, Any]:
    app_name = validate(app_name, APP_NAME_RE, "app_name")
    php_version = validate(php_version, PHP_VERSION_RE, "PHP version")
    mysql_service = validate(mysql_service or default_mysql_service(), MYSQL_SERVICE_RE, "MySQL service")
    app_uid = allocate_uid(app_name, uid, db)
    php_service = php_service_for(php_version)
    socket_group_name = stack_env().get("SOCKET_GROUP_NAME", "nginxsock")

    mkdir(app_home(app_name) / "logs", 0o770)
    mkdir(app_www(app_name))
    mkdir(app_home(app_name) / ".credentials", 0o700)
    mkdir(app_home(app_name) / ".composer")
    mkdir(app_home(app_name) / ".ssh", 0o700)
    mkdir(php_version_config_dir(php_version) / "users.d")
    mkdir(php_version_config_dir(php_version) / "pool.d")
    mkdir(cron_dir_for(php_version))
    mkdir(PHP_SOCKET_DIR / php_service)
    mkdir(PHP_LOG_DIR / php_service)

    fallback_path = php_version_config_dir(php_version) / "pool.d" / "zz-fallback.conf"
    if not fallback_path.exists():
        write_template(fallback_path, PHP_TEMPLATE_DIR / "fallback.conf.template", {"SOCKET_GROUP_NAME": socket_group_name}, generated=True)

    write_template(php_version_config_dir(php_version) / "users.d" / f"{app_name}.env", PHP_TEMPLATE_DIR / "user.env.template", {
        "USERNAME": app_name,
        "UID": app_uid,
    }, generated=True)
    write_template(php_version_config_dir(php_version) / "pool.d" / f"{app_name}.conf", PHP_TEMPLATE_DIR / "pool.conf.template", {
        "USERNAME": app_name,
        "SOCKET_GROUP_NAME": socket_group_name,
        "PHP_VERSION": php_version,
    }, generated=True)
    try:
        app_home(app_name).chmod(0o750)
    except PermissionError:
        warn(f"could not chmod home/{app_name}")

    info(f"Created PHP {php_version} app identity: {app_name} uid={app_uid}")
    info(f"Home: vibeops/{rel(app_home(app_name))}")
    info(f"Pool: vibeops/{rel(php_version_config_dir(php_version) / 'pool.d' / f'{app_name}.conf')}")
    info(f"Socket: vibeops/{rel(PHP_SOCKET_DIR / php_service / f'{app_name}.sock')}")

    php_reload(php_service, app_name, no_reload=no_reload)

    mysql_created = False
    credential_path = None
    if not no_mysql:
        mysql_created, credential_path = create_mysql_user(app_name, mysql_password, mysql_service)

    app = db["apps"].setdefault(app_name, {"name": app_name})
    app["uid"] = app_uid
    app["home"] = rel(app_home(app_name))
    public_dir = validate_public_dir(app.get("public_dir", ""))
    app["public_dir"] = public_dir
    app["root"] = rel(app_document_root(app_name, public_dir))
    app["php_version"] = php_version
    app["php_service"] = php_service
    versions = set(app.get("php_versions", []))
    versions.add(php_version)
    app["php_versions"] = sorted(versions)
    app.setdefault("databases", [])
    app.setdefault("tls", {"mode": "self-signed"})
    apply_app_mysql_metadata(app, app_name, mysql_service, credential_path)
    if mysql_created:
        app["mysql_user"] = True
    upsert_timestamp(app)
    return app


def tls_replacement(tls: dict[str, Any] | None) -> str:
    tls = tls or {"mode": "self-signed"}
    mode = tls.get("mode", "self-signed")
    if mode == "acme":
        return template_text(NGINX_TEMPLATE_DIR / "tls-acme.conf.template", {})
    if mode == "files":
        return template_text(NGINX_TEMPLATE_DIR / "tls-files.conf.template", {
            "CERT_PATH": tls.get("cert", ""),
            "CERT_KEY_PATH": tls.get("key", ""),
        })
    return template_text(NGINX_TEMPLATE_DIR / "tls-self-signed.conf.template", {})


def apply_vhost_tls(conf_path: Path, record: dict[str, Any]) -> None:
    tls = record.get("tls") if isinstance(record.get("tls"), dict) else {"mode": "self-signed"}
    replace_tls_block(conf_path, tls_replacement(tls))
    set_https_redirect(conf_path, bool(tls.get("redirect_https")) and tls.get("mode") in {"acme", "files"}, quiet=True)


def render_php_fallback(php_version: str) -> Path:
    php_version = validate(php_version, PHP_VERSION_RE, "PHP version")
    socket_group_name = stack_env().get("SOCKET_GROUP_NAME", "nginxsock")
    mkdir(php_version_config_dir(php_version) / "pool.d")
    fallback_path = php_version_config_dir(php_version) / "pool.d" / "zz-fallback.conf"
    write_template(fallback_path, PHP_TEMPLATE_DIR / "fallback.conf.template", {"SOCKET_GROUP_NAME": socket_group_name}, generated=True)
    return fallback_path


def render_app_identity(app: dict[str, Any]) -> None:
    app_name = validate(str(app.get("name", "")), APP_NAME_RE, "app_name")
    php_version = validate(str(app.get("php_version") or default_php_version()), PHP_VERSION_RE, "PHP version")
    php_service = php_service_for(php_version)
    uid = int(app.get("uid") or read_uid_from_env(php_version_config_dir(php_version) / "users.d" / f"{app_name}.env") or read_uid_from_env(LEGACY_PHP_VERSIONS_DIR / php_version / "users.d" / f"{app_name}.env") or allocate_uid(app_name, None, {"apps": {app_name: app}}))
    socket_group_name = stack_env().get("SOCKET_GROUP_NAME", "nginxsock")
    mkdir(php_version_config_dir(php_version) / "users.d")
    mkdir(php_version_config_dir(php_version) / "pool.d")
    mkdir(PHP_SOCKET_DIR / php_service)
    mkdir(PHP_LOG_DIR / php_service)
    render_php_fallback(php_version)
    write_template(php_version_config_dir(php_version) / "users.d" / f"{app_name}.env", PHP_TEMPLATE_DIR / "user.env.template", {
        "USERNAME": app_name,
        "UID": uid,
    }, generated=True)
    write_template(php_version_config_dir(php_version) / "pool.d" / f"{app_name}.conf", PHP_TEMPLATE_DIR / "pool.conf.template", {
        "USERNAME": app_name,
        "SOCKET_GROUP_NAME": socket_group_name,
        "PHP_VERSION": php_version,
    }, generated=True)
    app["uid"] = uid
    app["php_service"] = php_service
    app["home"] = rel(app_home(app_name))
    public_dir = validate_public_dir(str(app.get("public_dir", "")))
    app["root"] = rel(app_document_root(app_name, public_dir))


def render_app_vhost(app: dict[str, Any]) -> Path:
    app_name = str(app["name"])
    domains = app.get("domains") or [app.get("main_domain")]
    server_names = " ".join(str(d) for d in domains if d)
    conf_path = app_vhost_path(app_name)
    public_dir = validate_public_dir(str(app.get("public_dir", "")))
    render_template(NGINX_TEMPLATE_DIR / "site.conf.template", conf_path, {
        "USERNAME": app_name,
        "APP_NAME": app_name,
        "MAIN_DOMAIN": app.get("main_domain", ""),
        "SERVER_NAMES": server_names,
        "PHP_SERVICE": app.get("php_service") or php_service_for(str(app.get("php_version") or default_php_version())),
        "DOCUMENT_ROOT": container_document_root(app_name, public_dir),
    })
    apply_vhost_tls(conf_path, app)
    app["vhost"] = rel(conf_path)
    return conf_path


def cmd_app_create(args: argparse.Namespace) -> None:
    db = load_db()
    app_name = validate(args.app_name, APP_NAME_RE, "app_name")
    main_domain = validate(args.main_domain, DOMAIN_RE, "main domain")
    php_version = validate(args.php, PHP_VERSION_RE, "PHP version")
    mysql_service = validate(args.mysql_service, MYSQL_SERVICE_RE, "MySQL service")
    if args.no_mysql and args.db_suffix:
        die("Cannot create a database suffix with --no-mysql")
    public_dir = validate_public_dir(getattr(args, "public_dir", ""))
    aliases = normalize_aliases(args.alias, args.aliases)
    all_domains = domains_for(main_domain, aliases)
    for domain in all_domains:
        assert_domain_free(domain, db, allow_app=app_name)

    app = ensure_app_identity(app_name, php_version, db, uid=args.uid, no_mysql=args.no_mysql, mysql_password=getattr(args, "mysql_password", None), mysql_service=mysql_service, no_reload=args.no_reload)
    if app.get("main_domain") and app.get("main_domain") != main_domain:
        die(f"App {app_name} already has main domain {app.get('main_domain')}; use app domain set-main")
    old_domains = set(app.get("domains") or [])
    app["main_domain"] = main_domain
    app["domains"] = all_domains
    app["public_dir"] = public_dir
    app["root"] = rel(app_document_root(app_name, public_dir))
    mkdir(app_document_root(app_name, public_dir))
    for old_domain in old_domains - set(all_domains):
        owner = db.get("domains", {}).get(old_domain)
        if owner and owner.get("kind") == "php" and owner.get("app") == app_name:
            db["domains"].pop(old_domain, None)
    apply_app_mysql_metadata(app, app_name, mysql_service, app.get("mysql_credentials"))

    index_path = app_document_root(app_name, public_dir) / "index.php"
    if not args.no_index and not index_path.exists():
        write_template(index_path, PHP_TEMPLATE_DIR / "index.php.template", {"MAIN_DOMAIN": main_domain, "PHP_VERSION": php_version})

    if args.db_suffix:
        db_full_name = create_database(app_name, args.db_suffix, mysql_service)
        if db_full_name and db_full_name not in app.setdefault("databases", []):
            app["databases"].append(db_full_name)
        if db_full_name:
            app.setdefault("database_services", {})[db_full_name] = mysql_service

    conf_path = render_app_vhost(app)
    for domain in all_domains:
        db["domains"][domain] = {"kind": "php", "app": app_name}
    upsert_timestamp(app)
    save_db(db)

    info(f"Created HTTP+HTTPS app vhost: vibeops/{rel(conf_path)}")
    info(f"Document root: vibeops/{rel(app_document_root(app_name, public_dir))}")
    info(f"PHP-FPM: {php_version} via /run/php-fpm/{php_service_for(php_version)}/{app_name}.sock")
    nginx_reload(args.no_reload)


def ensure_app(app_name: str, php_version: str, db: dict[str, Any], no_reload: bool = False, mysql_service: str | None = None) -> dict[str, Any]:
    if app_name in db.get("apps", {}) and (php_version_config_dir(php_version) / "users.d" / f"{app_name}.env").exists():
        return db["apps"][app_name]
    info(f"PHP {php_version} app identity {app_name} does not exist; creating it first.")
    return ensure_app_identity(app_name, php_version, db, mysql_service=mysql_service, no_reload=no_reload)


def cmd_app_domain_add(args: argparse.Namespace) -> None:
    db = load_db()
    app_name = validate(args.app_name, APP_NAME_RE, "app_name")
    domain = validate(args.domain, DOMAIN_RE, "domain")
    app = db.get("apps", {}).get(app_name)
    if not isinstance(app, dict) or not app.get("main_domain"):
        die(f"Unknown app or app has no vhost: {app_name}")
    assert_domain_free(domain, db, allow_app=app_name)
    domains = list(app.get("domains") or [app["main_domain"]])
    if domain not in domains:
        domains.append(domain)
    app["domains"] = domains
    db["domains"][domain] = {"kind": "php", "app": app_name}
    render_app_vhost(app)
    upsert_timestamp(app)
    save_db(db)
    info(f"Added domain {domain} to app {app_name}")
    nginx_reload(args.no_reload)


def cmd_app_domain_remove(args: argparse.Namespace) -> None:
    db = load_db()
    app_name = validate(args.app_name, APP_NAME_RE, "app_name")
    domain = validate(args.domain, DOMAIN_RE, "domain")
    app = db.get("apps", {}).get(app_name)
    if not isinstance(app, dict):
        die(f"Unknown app: {app_name}")
    if domain == app.get("main_domain"):
        die("Cannot remove the main domain; use app domain set-main first")
    domains = [d for d in app.get("domains", []) if d != domain]
    if len(domains) == len(app.get("domains", [])):
        die(f"Domain {domain} is not on app {app_name}")
    app["domains"] = domains
    db.get("domains", {}).pop(domain, None)
    render_app_vhost(app)
    upsert_timestamp(app)
    save_db(db)
    info(f"Removed domain {domain} from app {app_name}")
    nginx_reload(args.no_reload)


def cmd_app_domain_set_main(args: argparse.Namespace) -> None:
    db = load_db()
    app_name = validate(args.app_name, APP_NAME_RE, "app_name")
    domain = validate(args.domain, DOMAIN_RE, "domain")
    app = db.get("apps", {}).get(app_name)
    if not isinstance(app, dict):
        die(f"Unknown app: {app_name}")
    domains = list(app.get("domains") or [])
    if domain not in domains:
        die(f"Domain {domain} is not on app {app_name}; add it first")
    app["main_domain"] = domain
    app["domains"] = [domain] + [d for d in domains if d != domain]
    render_app_vhost(app)
    upsert_timestamp(app)
    save_db(db)
    info(f"Set main domain for {app_name}: {domain}")
    nginx_reload(args.no_reload)


def cmd_app_list(args: argparse.Namespace) -> None:
    db = load_db()
    apps = db.get("apps", {})
    if not apps:
        info("No apps in stack.json. Create one with: ./manage.py app create <app_name> <main_domain>")
        return
    for name, app in sorted(apps.items()):
        if not isinstance(app, dict):
            continue
        domains = ",".join(app.get("domains", []) or [])
        info(f"{name}\tphp={app.get('php_version', '')}\tmain={app.get('main_domain', '')}\tdomains={domains}")


def cmd_app_show(args: argparse.Namespace) -> None:
    db = load_db()
    app_name = validate(args.app_name, APP_NAME_RE, "app_name")
    app = db.get("apps", {}).get(app_name)
    if not isinstance(app, dict):
        die(f"Unknown app: {app_name}")
    print(json.dumps(app, indent=2, sort_keys=True))


def cmd_user_create(args: argparse.Namespace, *, db: dict[str, Any] | None = None, save: bool = True) -> None:
    warn("'user create' is deprecated; use 'app create <app_name> <main_domain>' for deployable apps")
    db = db if db is not None else load_db()
    ensure_app_identity(args.username, args.php, db, uid=args.uid, no_mysql=args.no_mysql, mysql_password=args.mysql_password, mysql_service=args.mysql_service, no_reload=args.no_reload)
    if save:
        save_db(db)


def ensure_user(username: str, php_version: str, db: dict[str, Any], no_reload: bool = False, mysql_service: str | None = None) -> None:
    ensure_app(username, php_version, db, no_reload=no_reload, mysql_service=mysql_service)


def cmd_site_create(args: argparse.Namespace) -> None:
    db = load_db()
    app_name = validate(args.username, APP_NAME_RE, "app_name")
    domain = validate(args.domain, DOMAIN_RE, "domain")
    if app_name not in db.get("apps", {}) and not app_home(app_name).exists():
        warn("'site create' is deprecated; creating an app instead")
        ns = argparse.Namespace(app_name=app_name, main_domain=domain, db_suffix=args.db_name, php=args.php, mysql_service=args.mysql_service, alias=args.alias, aliases=args.aliases, public_dir="", no_index=args.no_index, no_reload=args.no_reload, uid=None, no_mysql=False, mysql_password=None)
        cmd_app_create(ns)
        return
    app = db.get("apps", {}).get(app_name)
    if isinstance(app, dict) and domain in (app.get("domains") or []):
        render_app_vhost(app)
        save_db(db)
        info(f"Regenerated app vhost for {app_name}")
        return
    die("site create is deprecated and multi-site users are no longer supported. Use either:\n  ./manage.py app domain add {0} {1}   # same codebase\n  ./manage.py app create <new_app> {1} {2}   # new isolation".format(app_name, domain, args.db_name or ""))


def render_proxy_vhost(site: dict[str, Any]) -> Path:
    main_domain = str(site["domain"])
    aliases = list(site.get("aliases") or [])
    server_names = " ".join([main_domain] + aliases)
    conf_path = NGINX_VHOST_DIR / f"{main_domain}.conf"
    render_template(NGINX_TEMPLATE_DIR / "proxy.conf.template", conf_path, {
        "MAIN_DOMAIN": main_domain,
        "SERVER_NAMES": server_names,
        "UPSTREAM": site.get("upstream", ""),
    })
    apply_vhost_tls(conf_path, site)
    site["vhost"] = rel(conf_path)
    return conf_path


def cmd_proxy_create(args: argparse.Namespace) -> None:
    db = load_db()
    main_domain = validate(args.domain, DOMAIN_RE, "domain")
    upstream = args.upstream
    if not upstream:
        die("upstream is required")
    aliases = normalize_aliases(args.alias, args.aliases)
    for domain in domains_for(main_domain, aliases):
        assert_domain_free(domain, db, allow_domain=main_domain)

    site = db["sites"].setdefault(main_domain, {})
    site.update({
        "type": "proxy",
        "domain": main_domain,
        "aliases": aliases,
        "upstream": upstream,
        "tls": site.get("tls", {"mode": "self-signed"}),
    })
    conf_path = render_proxy_vhost(site)
    info(f"Created HTTP+HTTPS proxy vhost with default self-signed cert: vibeops/{rel(conf_path)}")
    new_domains = set(domains_for(main_domain, aliases))
    for old_domain, owner in list(db.get("domains", {}).items()):
        if owner.get("kind") == "proxy" and owner.get("domain") == main_domain and old_domain not in new_domains:
            db["domains"].pop(old_domain, None)
    for domain in sorted(new_domains):
        db["domains"][domain] = {"kind": "proxy", "domain": main_domain}
    upsert_timestamp(site)
    save_db(db)
    nginx_reload(args.no_reload)



def safe_app_part(app_name: str) -> str:
    return re.sub(r"[^A-Za-z0-9_.-]", "_", app_name)


def safe_domain_part(domain: str) -> str:
    return re.sub(r"[^A-Za-z0-9_.-]", "_", domain)


def cmd_cron_create(args: argparse.Namespace) -> None:
    db = load_db()
    app_name = validate(args.app_name, APP_NAME_RE, "app_name")
    job_name = validate(args.job_name, JOB_RE, "job-name")
    php_version = validate(args.php, PHP_VERSION_RE, "PHP version")
    schedule = args.schedule
    command = args.command
    if not schedule or not command:
        die("schedule and command are required")
    php_service = php_cron_service_for(php_version)
    workdir = args.workdir or f"/home/{app_name}/{DOCROOT_NAME}"

    ensure_app(app_name, php_version, db)
    mkdir(cron_jobs_dir_for(php_version))
    mkdir(app_www(app_name))

    cron_path = cron_jobs_dir_for(php_version) / f"{safe_app_part(app_name)}-{job_name}.cron"
    write_template(cron_path, PHP_TEMPLATE_DIR / "cron.cron.template", {
        "USERNAME": app_name,
        "APP_NAME": app_name,
        "DOMAIN": DOCROOT_NAME,
        "PHP_VERSION": php_version,
        "PHP_SERVICE": php_service,
        "SCHEDULE": schedule,
        "QUOTED_USERNAME": shlex.quote(app_name),
        "QUOTED_WORKDIR": shlex.quote(workdir),
        "QUOTED_COMMAND": shlex.quote(command),
    }, 0o644, generated=True)

    info(f"Created cron job: vibeops/{rel(cron_path)}")
    info(f"Runs as: {app_name}")
    info(f"Workdir: {workdir}")
    combined_crontab = rebuild_supercronic_crontab(php_version)
    info(f"Updated Supercronic crontab: vibeops/{rel(combined_crontab)}")
    info(f"Command: {command}")

    cron_key = f"{app_name}/{job_name}"
    cron = db["crons"].setdefault(cron_key, {})
    cron.update({
        "app": app_name,
        "job_name": job_name,
        "php_version": php_version,
        "php_service": php_service,
        "schedule": schedule,
        "command": command,
        "workdir": workdir,
        "file": rel(cron_path),
    })
    upsert_timestamp(cron)
    save_db(db)
    cron_reload(php_service, [app_name])


def cmd_cron_reload(args: argparse.Namespace) -> None:
    php_version = validate(args.php, PHP_VERSION_RE, "PHP version")
    combined_crontab = rebuild_supercronic_crontab(php_version)
    info(f"Updated Supercronic crontab: vibeops/{rel(combined_crontab)}")
    cron_reload(php_cron_service_for(php_version))


def replace_tls_block(conf_path: Path, replacement: str) -> None:
    text = conf_path.read_text()
    text2, count = re.subn(r"# BEGIN TLS_CERTIFICATE\n.*?\n\s*# END TLS_CERTIFICATE", lambda _: replacement, text, count=1, flags=re.S)
    if count != 1:
        die(f"Could not find marked TLS certificate block in {rel(conf_path)}")
    write_text(conf_path, text2)


def set_https_redirect(conf_path: Path, enabled: bool, *, quiet: bool = False) -> None:
    """Toggle the generated HTTP vhost redirect flag."""
    text = conf_path.read_text()
    value = "1" if enabled else "0"

    if "set $enable_https_redirect" in text:
        text2, count = re.subn(r"set \$enable_https_redirect [01];", f"set $enable_https_redirect {value};", text, count=1)
    else:
        listen_pos = text.find("listen 80;")
        server_name_pos = text.find("server_name ", listen_pos)
        insert_pos = text.find(";", server_name_pos) + 1 if server_name_pos >= 0 else 0
        if listen_pos < 0 or server_name_pos < 0 or insert_pos <= 0:
            warn(f"Could not find generated HTTP server in {rel(conf_path)}; skipped HTTPS redirect toggle")
            return
        text2 = text[:insert_pos] + f"\n\n    set $enable_https_redirect {value};" + text[insert_pos:]
        count = 1

    if count and text2 != text:
        write_text(conf_path, text2)
        if not quiet:
            info(("Enabled" if enabled else "Disabled") + f" HTTP to HTTPS redirect in vibeops/{rel(conf_path)}")


def vhost_for_domain(domain: str, db: dict[str, Any]) -> tuple[Path, dict[str, Any] | None]:
    owner = db.get("domains", {}).get(domain)
    if owner and owner.get("kind") == "php":
        app = db.get("apps", {}).get(owner.get("app"))
        if not isinstance(app, dict):
            die(f"Domain {domain} points to missing app {owner.get('app')}")
        return ROOT / str(app.get("vhost", rel(app_vhost_path(str(app.get("name")))))), app
    if owner and owner.get("kind") == "proxy":
        site = db.get("sites", {}).get(owner.get("domain"))
        if isinstance(site, dict):
            return ROOT / str(site.get("vhost", rel(NGINX_VHOST_DIR / f"{owner.get('domain')}.conf"))), site
    site = db.get("sites", {}).get(domain)
    if isinstance(site, dict):
        return ROOT / str(site.get("vhost", rel(NGINX_VHOST_DIR / f"{domain}.conf"))), site
    return NGINX_VHOST_DIR / f"{domain}.conf", None


def cmd_tls_acme(args: argparse.Namespace) -> None:
    db = load_db()
    main_domain = validate(args.domain, DOMAIN_RE, "domain")
    conf_path, record = vhost_for_domain(main_domain, db)
    if not conf_path.exists():
        die(f"Missing vhost: vibeops/{rel(conf_path)}")
    if args.off:
        replacement = template_text(NGINX_TEMPLATE_DIR / "tls-self-signed.conf.template", {})
        mode = "self-signed"
    else:
        replacement = template_text(NGINX_TEMPLATE_DIR / "tls-acme.conf.template", {})
        mode = "acme"
    replace_tls_block(conf_path, replacement)
    set_https_redirect(conf_path, mode == "acme" and not args.no_redirect_https)
    record = record or db["sites"].setdefault(main_domain, {"domain": main_domain, "vhost": rel(conf_path)})
    record["tls"] = {"mode": mode, "redirect_https": mode == "acme" and not args.no_redirect_https}
    upsert_timestamp(record)
    save_db(db)
    info(("Enabled NGINX ACME for" if mode == "acme" else "Switched to self-signed certificate for") + f" {main_domain}")
    nginx_reload(args.no_reload)


def cmd_tls_cert(args: argparse.Namespace) -> None:
    db = load_db()
    main_domain = validate(args.domain, DOMAIN_RE, "domain")
    conf_path, record = vhost_for_domain(main_domain, db)
    if not conf_path.exists():
        die(f"Missing vhost: vibeops/{rel(conf_path)}")
    cert_path = args.cert or f"/etc/letsencrypt/live/{main_domain}/fullchain.pem"
    key_path = args.key or f"/etc/letsencrypt/live/{main_domain}/privkey.pem"
    replacement = template_text(NGINX_TEMPLATE_DIR / "tls-files.conf.template", {
        "CERT_PATH": cert_path,
        "CERT_KEY_PATH": key_path,
    })
    replace_tls_block(conf_path, replacement)

    for container_path, label in [(cert_path, "cert"), (key_path, "key")]:
        if container_path.startswith("/etc/letsencrypt/"):
            host_path = CERTS_DIR / container_path.removeprefix("/etc/letsencrypt/")
            if not host_path.exists():
                warn(f"expected host {label} file vibeops/{rel(host_path)} was not found")

    record = record or db["sites"].setdefault(main_domain, {"domain": main_domain, "vhost": rel(conf_path)})
    record["tls"] = {"mode": "files", "cert": cert_path, "key": key_path}
    upsert_timestamp(record)
    save_db(db)
    info(f"Switched {main_domain} to certificate files:")
    info(f"  cert: {cert_path}")
    info(f"  key:  {key_path}")
    nginx_reload(args.no_reload)



def select_app_from_db() -> tuple[str, str]:
    db = load_db()
    apps = [app for app in db.get("apps", {}).values() if isinstance(app, dict) and app.get("name")]
    apps.sort(key=lambda a: str(a.get("name")))
    if not apps:
        die("No apps in state. Create one with: ./manage.py app create <app_name> <main_domain>")
    if len(apps) == 1:
        app = apps[0]
        return str(app["name"]), str(app.get("php_version") or default_php_version())
    if not sys.stdin.isatty():
        choices = ", ".join(str(app.get("name")) for app in apps)
        die(f"Multiple apps found in state; choose one explicitly. Apps: {choices}")
    info("Select app:")
    for idx, app in enumerate(apps, start=1):
        info(f"  {idx}) {app.get('name')}  main={app.get('main_domain', '-')}  php={app.get('php_version', default_php_version())}")
    while True:
        raw = input("App number: ").strip()
        try:
            choice = int(raw)
        except ValueError:
            choice = 0
        if 1 <= choice <= len(apps):
            app = apps[choice - 1]
            return str(app["name"]), str(app.get("php_version") or default_php_version())
        warn("invalid selection")


def cmd_app_shell(args: argparse.Namespace) -> None:
    if not args.app_name:
        args.app_name, selected_php = select_app_from_db()
        if args.php == default_php_version():
            args.php = selected_php
    args.command = [args.shell]
    cmd_app_exec(args)


def cmd_app_exec(args: argparse.Namespace) -> None:
    app_name = validate(args.app_name, APP_NAME_RE, "app_name")
    php_version = validate(args.php, PHP_VERSION_RE, "PHP version")
    php_service = php_service_for(php_version)
    php_cli_service = php_cli_service_for(php_version)
    workdir = args.workdir or f"/home/{app_name}/{DOCROOT_NAME}"
    command = args.command or ["sh"]
    if command and command[0] == "--":
        command = command[1:] or ["sh"]

    db = load_db()
    ensure_app(app_name, php_version, db)
    save_db(db)

    if not docker_available():
        die("docker is required")
    if service_running(php_service):
        run(["docker", "compose", "exec", "-T", php_service, "php-user-sync", app_name], check=False)

    tty_args: list[str] = []
    if not sys.stdin.isatty() or not sys.stdout.isatty():
        tty_args.append("-T")
    os.execvp("docker", [
        "docker", "compose", "run", "--rm", *tty_args,
        php_cli_service,
        "php-cron-as", app_name, workdir,
        *command,
    ])


def cmd_list(args: argparse.Namespace) -> None:
    db = load_db()
    kind = args.kind
    if kind == "apps":
        cmd_app_list(args)
    elif kind == "domains":
        domains = db.get("domains", {})
        if not domains:
            info("No domains in state.")
            return
        for domain, owner in sorted(domains.items()):
            if owner.get("kind") == "php":
                info(f"{domain}\tphp\tapp={owner.get('app', '')}")
            else:
                info(f"{domain}\tproxy\tvhost={owner.get('domain', '')}")
    elif kind in {"users", "sites"}:
        warn(f"'list {kind}' is deprecated; use 'list apps' or 'list domains'")
        cmd_list(argparse.Namespace(kind="apps" if kind == "users" else "domains"))
    elif kind == "crons":
        crons = db.get("crons", {})
        if not crons:
            info("No crons in state. Create one with: ./manage.py cron create <app_name> <name> '<schedule>' '<command>'")
            return
        for key, cron in sorted(crons.items()):
            if not isinstance(cron, dict):
                continue
            info(f"{key}\t{cron.get('schedule', '')}\t{cron.get('command', '')}")
    else:
        print(json.dumps(db, indent=2, sort_keys=True))


def render_cron_job(cron: dict[str, Any]) -> Path:
    app_name = validate(str(cron.get("app", "")), APP_NAME_RE, "app_name")
    job_name = validate(str(cron.get("job_name", "")), JOB_RE, "job-name")
    php_version = validate(str(cron.get("php_version") or default_php_version()), PHP_VERSION_RE, "PHP version")
    php_service = php_cron_service_for(php_version)
    workdir = str(cron.get("workdir") or f"/home/{app_name}/{DOCROOT_NAME}")
    cron_path = cron_jobs_dir_for(php_version) / f"{safe_app_part(app_name)}-{job_name}.cron"
    mkdir(cron_jobs_dir_for(php_version))
    write_template(cron_path, PHP_TEMPLATE_DIR / "cron.cron.template", {
        "USERNAME": app_name,
        "APP_NAME": app_name,
        "DOMAIN": DOCROOT_NAME,
        "PHP_VERSION": php_version,
        "PHP_SERVICE": php_service,
        "SCHEDULE": cron.get("schedule", ""),
        "QUOTED_USERNAME": shlex.quote(app_name),
        "QUOTED_WORKDIR": shlex.quote(workdir),
        "QUOTED_COMMAND": shlex.quote(str(cron.get("command", ""))),
    }, 0o644, generated=True)
    cron["php_service"] = php_service
    cron["file"] = rel(cron_path)
    return cron_path


def clean_generated_config() -> None:
    patterns = [
        "nginx/vhosts/*.conf",
        "php/versions/*/users.d/*.env",
        "php/versions/*/pool.d/*.conf",
        "cron/php*/jobs/*.cron",
        "cron/php*/.supercronic.cron",
    ]
    for pattern in patterns:
        for path in GENERATED_DIR.glob(pattern):
            if path.name != ".gitkeep":
                path.unlink(missing_ok=True)


def render_all(db: dict[str, Any]) -> list[Path]:
    clean_generated_config()
    rendered: list[Path] = []
    php_versions = set(available_php_versions())
    php_versions.update(str(app.get("php_version") or default_php_version()) for app in db.get("apps", {}).values() if isinstance(app, dict))
    for version in sorted(php_versions):
        rendered.append(render_php_fallback(version))
    for app_name, app in sorted(db.get("apps", {}).items()):
        if not isinstance(app, dict):
            continue
        app.setdefault("name", app_name)
        mkdir(app_home(app_name) / "logs", 0o770)
        mkdir(app_www(app_name))
        render_app_identity(app)
        if app.get("main_domain"):
            rendered.append(render_app_vhost(app))
    for domain, site in sorted(db.get("sites", {}).items()):
        if isinstance(site, dict) and site.get("type") == "proxy":
            site.setdefault("domain", domain)
            rendered.append(render_proxy_vhost(site))
    cron_versions: set[str] = set()
    for cron in db.get("crons", {}).values():
        if not isinstance(cron, dict):
            continue
        path = render_cron_job(cron)
        rendered.append(path)
        cron_versions.add(str(cron.get("php_version") or default_php_version()))
    for version in sorted(cron_versions):
        rendered.append(rebuild_supercronic_crontab(version))
    return rendered


def compose_files() -> list[Path]:
    files = [ROOT / "compose.yml"]
    for path in [ROOT / "compose.override.yml", ROOT / "compose.local.yml"]:
        if path.exists():
            files.append(path)
    compose_d = ROOT / "compose.d"
    if compose_d.exists():
        files.extend(sorted(compose_d.glob("*.yml")))
        files.extend(sorted(compose_d.glob("*.yaml")))
    return files


def cmd_compose(args: argparse.Namespace) -> None:
    files = compose_files()
    cmd = ["docker", "compose"]
    for path in files:
        cmd.extend(["-f", str(path)])
    cmd.extend(args.compose_args or ["ps"])
    os.execvp("docker", cmd)


def cmd_render(args: argparse.Namespace) -> None:
    db = load_db()
    rendered = render_all(db)
    save_db(db)
    info(f"Rendered {len(rendered)} file(s) from vibeops/{rel(DB_PATH)}")
    for path in rendered:
        info(f"  {rel(path)}")


def cmd_apply(args: argparse.Namespace) -> None:
    db = load_db()
    rendered = render_all(db)
    save_db(db)
    info(f"Rendered {len(rendered)} file(s)")
    if args.no_reload:
        return
    if docker_available() and service_running("nginx"):
        run(["docker", "compose", "exec", "-T", "nginx", "nginx", "-t"])
    nginx_reload(False)
    php_versions = {str(app.get("php_version") or default_php_version()) for app in db.get("apps", {}).values() if isinstance(app, dict)}
    for version in sorted(php_versions):
        service = php_service_for(version)
        if service_running(service):
            run(["docker", "compose", "exec", "-T", service, "php-fpm", "-tt"])
            run(["docker", "compose", "kill", "-s", "USR2", service], check=False)
    cron_versions = {str(cron.get("php_version") or default_php_version()) for cron in db.get("crons", {}).values() if isinstance(cron, dict)}
    for version in sorted(cron_versions):
        cron_reload(php_cron_service_for(version))


def cmd_state(args: argparse.Namespace) -> None:
    if args.state_action == "path":
        info(str(DB_PATH))
    elif args.state_action == "show":
        print(json.dumps(load_db(), indent=2, sort_keys=True))
    elif args.state_action == "migrate":
        if DB_PATH.exists() and not args.force:
            die(f"{rel(DB_PATH)} already exists; use --force to overwrite")
        data = load_db()
        save_db(data)
        if LEGACY_DB_PATH.exists() and LEGACY_DB_PATH != DB_PATH:
            backup = LEGACY_DB_PATH.with_suffix(".json.legacy")
            if not backup.exists():
                LEGACY_DB_PATH.rename(backup)
                info(f"Moved legacy state to vibeops/{rel(backup)}")
            else:
                warn(f"legacy state remains at {rel(LEGACY_DB_PATH)} because {rel(backup)} already exists")
        info(f"Migrated state to vibeops/{rel(DB_PATH)}")
    elif args.state_action == "init":
        if DB_PATH.exists() and not args.force:
            die(f"{rel(DB_PATH)} already exists; use --force to overwrite")
        save_db(empty_db())
        info(f"Initialized vibeops/{rel(DB_PATH)}")


def prompt_text(label: str, default: str | None = None, *, required: bool = True) -> str:
    suffix = f" [{default}]" if default not in (None, "") else ""
    while True:
        value = input(f"{label}{suffix}: ").strip()
        if not value and default is not None:
            value = default
        if value or not required:
            return value
        warn("required")


def prompt_validated(label: str, pattern: re.Pattern[str], value_label: str, default: str | None = None, *, required: bool = True, hint: str | None = None) -> str:
    while True:
        value = prompt_text(label, default, required=required)
        if not value and not required:
            return value
        if pattern.match(value):
            return value
        warn(f"invalid {value_label}: {value}" + (f" ({hint})" if hint else ""))


def prompt_int(label: str, default: str | None = None, *, required: bool = False) -> int | None:
    while True:
        value = prompt_text(label, default, required=required)
        if not value:
            return None
        try:
            return int(value)
        except ValueError:
            warn(f"invalid integer: {value}")


def prompt_public_dir() -> str:
    while True:
        raw = prompt_text("Public dir inside www (blank = www, Laravel: public)", "", required=False)
        try:
            return validate_public_dir(raw)
        except StackError as exc:
            warn(str(exc))


def prompt_aliases() -> list[str]:
    while True:
        raw = prompt_text("Aliases, comma-separated (blank = none)", "", required=False)
        aliases = parse_csv(raw)
        invalid = [a for a in aliases if not DOMAIN_RE.match(a)]
        if not invalid:
            return aliases
        warn("invalid alias domain(s): " + ", ".join(invalid))


def prompt_confirm(label: str, default: bool = True) -> bool:
    suffix = "Y/n" if default else "y/N"
    while True:
        value = input(f"{label} [{suffix}]: ").strip().lower()
        if not value:
            return default
        if value in {"y", "yes"}:
            return True
        if value in {"n", "no"}:
            return False
        warn("answer yes or no")


def prompt_choice(label: str, choices: list[str], default: str | None = None) -> str:
    if not choices:
        return prompt_text(label, default)
    info(label + ":")
    for idx, choice in enumerate(choices, start=1):
        marker = " *" if choice == default else ""
        info(f"  {idx}) {choice}{marker}")
    while True:
        raw = input(f"Choose 1-{len(choices)}" + (f" [{default}]" if default else "") + ": ").strip()
        if not raw and default:
            return default
        try:
            idx = int(raw)
        except ValueError:
            idx = 0
        if 1 <= idx <= len(choices):
            return choices[idx - 1]
        warn("invalid selection")


def available_php_versions() -> list[str]:
    version_set: set[str] = set()
    for base in (LEGACY_PHP_VERSIONS_DIR, PHP_VERSIONS_DIR):
        if base.exists():
            version_set.update(p.name for p in base.iterdir() if p.is_dir())
    versions = sorted(version_set)
    default = default_php_version()
    if default not in versions:
        versions.insert(0, default)
    return versions


def parse_csv(value: str) -> list[str]:
    return [item.strip() for item in value.split(",") if item.strip()]


def print_plan(lines: list[str]) -> None:
    info("\nPlan:")
    for line in lines:
        info(f"  - {line}")


def cmd_status(args: argparse.Namespace) -> None:
    db = load_db()
    services = ["mysql57", "mysql84", "mysql97", "redis", "nginx", "php84", "php85", "php84-cron", "php85-cron"]
    running = running_services()
    info("VibeOps status\n")
    info("Docker services:")
    if not docker_available():
        info("  docker: not found")
    else:
        for service in services:
            info(f"  {service:<10} {'running' if service in running else '-'}")
    info("\nApps:")
    apps = db.get("apps", {})
    if not apps:
        info("  none")
    for name, app in sorted(apps.items()):
        if not isinstance(app, dict):
            continue
        tls = app.get("tls", {}).get("mode", "")
        info(f"  {name:<20} php={app.get('php_version', ''):<4} main={app.get('main_domain', '-')} tls={tls}")
    proxies = [s for s in db.get("sites", {}).values() if isinstance(s, dict) and s.get("type") == "proxy"]
    if proxies:
        info("\nProxies:")
        for site in sorted(proxies, key=lambda s: str(s.get("domain"))):
            info(f"  {site.get('domain', ''):<28} {site.get('upstream', '')} tls={site.get('tls', {}).get('mode', '')}")
    info("\nQuick checks:")
    info(f"  metadata: vibeops/{rel(DB_PATH)} {'exists' if DB_PATH.exists() else 'missing'}")
    info(f"  vhosts:   vibeops/{rel(NGINX_VHOST_DIR)}")
    if args.check_nginx and "nginx" in running:
        run(["docker", "compose", "exec", "-T", "nginx", "nginx", "-t"])


def wizard_create_user() -> None:
    username = prompt_validated("App name", APP_NAME_RE, "app_name", hint="use a Linux-safe slug like my_app or shop-api; lowercase, no spaces, max 32 chars")
    php = prompt_choice("PHP version", available_php_versions(), default_php_version())
    uid = prompt_int("UID (blank = auto)", "", required=False)
    no_mysql = not prompt_confirm("Create/update MySQL account?", True)
    mysql_service = default_mysql_service() if no_mysql else prompt_validated("MySQL service", MYSQL_SERVICE_RE, "MySQL service", default_mysql_service(), hint="for example mysql57, mysql84, mysql97")
    mysql_password = None if no_mysql else prompt_text("MySQL password (blank = generate)", "", required=False) or None
    no_reload = not prompt_confirm("Reload PHP-FPM if running?", True)
    print_plan([f"create/update app identity {username}", f"PHP {php}", "MySQL account: " + ("no" if no_mysql else mysql_service), "reload PHP-FPM: " + ("no" if no_reload else "yes")])
    if prompt_confirm("Continue?", True):
        cmd_user_create(argparse.Namespace(username=username, uid=uid, php=php, no_mysql=no_mysql, mysql_password=mysql_password, mysql_service=mysql_service, no_reload=no_reload))



def wizard_create_site() -> None:
    app_name = prompt_validated("App name", APP_NAME_RE, "app_name", hint="use a Linux-safe slug like my_app or shop-api; lowercase, no spaces, max 32 chars")
    domain = prompt_validated("Main domain", DOMAIN_RE, "domain")
    aliases = prompt_aliases()
    public_dir = prompt_public_dir()
    php = prompt_choice("PHP version", available_php_versions(), default_php_version())
    db_name = prompt_validated("Database suffix, e.g. app (blank = none)", DB_NAME_RE, "database suffix", "", required=False) or None
    mysql_service = prompt_validated("MySQL service", MYSQL_SERVICE_RE, "MySQL service", default_mysql_service(), hint="for example mysql57, mysql84, mysql97") if db_name else default_mysql_service()
    no_index = not prompt_confirm("Create starter index.php if missing?", True)
    no_reload = not prompt_confirm("Reload nginx/PHP-FPM if running?", True)
    plan = [f"create/update app {app_name} on PHP {php}", f"main domain {domain}", f"document root: /home/{app_name}/www" + (f"/{public_dir}" if public_dir else "")]
    if aliases:
        plan.append("aliases: " + ", ".join(aliases))
    if db_name:
        plan.append(f"database: {app_name}_{db_name} on {mysql_service}")
    plan.append("reload services: " + ("no" if no_reload else "yes"))
    print_plan(plan)
    info("\nEquivalent command:")
    alias_args = " ".join(f"--alias {shlex.quote(a)}" for a in aliases)
    public_dir_arg = f" --public-dir {shlex.quote(public_dir)}" if public_dir else ""
    info(f"  ./manage.py app create {shlex.quote(app_name)} {shlex.quote(domain)}" + (f" {shlex.quote(db_name)}" if db_name else "") + f" --php {shlex.quote(php)} --mysql-service {shlex.quote(mysql_service)}" + public_dir_arg + (f" {alias_args}" if alias_args else ""))
    if prompt_confirm("Continue?", True):
        cmd_app_create(argparse.Namespace(app_name=app_name, main_domain=domain, db_suffix=db_name, php=php, mysql_service=mysql_service, alias=aliases, aliases=None, public_dir=public_dir, no_index=no_index, no_reload=no_reload, uid=None, no_mysql=False, mysql_password=None))


def wizard_create_proxy() -> None:
    domain = prompt_validated("Domain", DOMAIN_RE, "domain")
    upstream = prompt_text("Upstream URL", "http://127.0.0.1:3000")
    aliases = prompt_aliases()
    no_reload = not prompt_confirm("Reload nginx if running?", True)
    print_plan([f"create/update proxy {domain}", f"upstream: {upstream}"] + (["aliases: " + ", ".join(aliases)] if aliases else []))
    if prompt_confirm("Continue?", True):
        cmd_proxy_create(argparse.Namespace(domain=domain, upstream=upstream, alias=aliases, aliases=None, no_reload=no_reload))


def wizard_tls_acme() -> None:
    db = load_db()
    domains = sorted(db.get("domains", {}).keys())
    domain = prompt_choice("Domain", domains) if domains else prompt_validated("Domain", DOMAIN_RE, "domain")
    off = not prompt_confirm("Enable ACME? (no switches back to self-signed)", True)
    no_redirect_https = False if off else not prompt_confirm("Redirect HTTP to HTTPS after ACME?", True)
    no_reload = not prompt_confirm("Reload nginx if running?", True)
    print_plan([(f"switch {domain} to self-signed" if off else f"enable ACME for {domain}"), "redirect HTTP to HTTPS: " + ("no" if no_redirect_https else "yes"), "reload nginx: " + ("no" if no_reload else "yes")])
    if prompt_confirm("Continue?", True):
        cmd_tls_acme(argparse.Namespace(domain=domain, off=off, no_redirect_https=no_redirect_https, no_reload=no_reload))


def wizard_cron() -> None:
    db = load_db()
    apps = [a for a in db.get("apps", {}).values() if isinstance(a, dict) and a.get("name")]
    labels = [f"{a.get('name')} (php {a.get('php_version', default_php_version())})" for a in apps]
    label = prompt_choice("App", labels) if labels else ""
    if label:
        app = apps[labels.index(label)]
        app_name = str(app.get("name"))
        php = str(app.get("php_version") or default_php_version())
    else:
        app_name = prompt_validated("App name", APP_NAME_RE, "app_name", hint="use a Linux-safe slug like my_app or shop-api; lowercase, no spaces, max 32 chars")
        php = prompt_choice("PHP version", available_php_versions(), default_php_version())
    job_name = prompt_validated("Job name", JOB_RE, "job name")
    schedule = prompt_text("Schedule", "* * * * *")
    command = prompt_text("Command", "php artisan schedule:run")
    workdir = prompt_text("Workdir (blank = /home/<app>/www)", "", required=False) or None
    print_plan([f"create/update cron {app_name}/{job_name}", f"schedule: {schedule}", f"command: {command}"])
    if prompt_confirm("Continue?", True):
        cmd_cron_create(argparse.Namespace(app_name=app_name, job_name=job_name, schedule=schedule, command=command, php=php, workdir=workdir))


def cmd_wizard(args: argparse.Namespace) -> None:
    if not sys.stdin.isatty():
        die("wizard requires an interactive terminal")
    actions = [
        "Create app identity",
        "Create app",
        "Create reverse proxy",
        "Enable/switch TLS ACME",
        "Create cron job",
        "Open app shell",
        "Show status",
        "List apps/domains/crons",
        "Quit",
    ]
    while True:
        info("\nVibeOps")
        action = prompt_choice("What do you want to do?", actions)
        if action == "Create app identity":
            wizard_create_user()
        elif action == "Create app":
            wizard_create_site()
        elif action == "Create reverse proxy":
            wizard_create_proxy()
        elif action == "Enable/switch TLS ACME":
            wizard_tls_acme()
        elif action == "Create cron job":
            wizard_cron()
        elif action == "Open app shell":
            cmd_app_shell(argparse.Namespace(app_name=None, php=default_php_version(), workdir=None, shell="bash"))
        elif action == "Show status":
            cmd_status(argparse.Namespace(check_nginx=False))
        elif action == "List apps/domains/crons":
            kind = prompt_choice("List", ["apps", "domains", "crons", "all"], "apps")
            cmd_list(argparse.Namespace(kind=kind))
        else:
            return
        if not prompt_confirm("Back to menu?", True):
            return


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="manage.py",
        description="Pure-Python management CLI for VibeOps, the vibe-coding ops stack.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.set_defaults(func=None)
    sub = parser.add_subparsers(dest="command")

    app = sub.add_parser("app", help="Manage isolated PHP apps")
    app_sub = app.add_subparsers(dest="app_command", required=True)
    app_create = app_sub.add_parser("create", help="Create/update an isolated app")
    app_create.add_argument("app_name")
    app_create.add_argument("main_domain")
    app_create.add_argument("db_suffix", nargs="?")
    app_create.add_argument("--php", default=default_php_version(), help="PHP version")
    app_create.add_argument("--mysql-service", default=default_mysql_service(), help="MySQL service for optional database creation, e.g. mysql57/mysql84/mysql97")
    app_create.add_argument("--alias", action="append", help="Additional server_name; can be passed multiple times or comma-separated")
    app_create.add_argument("--aliases", help="Comma-separated additional server names")
    app_create.add_argument("--public-dir", default="", help="Document root subdirectory inside /home/<app>/www, e.g. 'public' for Laravel; default is app root")
    app_create.add_argument("--no-mysql", action="store_true", help="Do not create/update the MySQL account")
    app_create.add_argument("--mysql-password", help="Password for the MySQL account")
    app_create.add_argument("--no-index", action="store_true", help="Do not create starter index.php")
    app_create.add_argument("--no-reload", action="store_true", help="Do not reload nginx/PHP-FPM")
    app_create.add_argument("--uid", type=int, help="Explicit Linux UID")
    app_create.set_defaults(func=cmd_app_create)
    app_domain = app_sub.add_parser("domain", help="Manage app domains")
    app_domain_sub = app_domain.add_subparsers(dest="domain_command", required=True)
    app_domain_add = app_domain_sub.add_parser("add", help="Add an alias domain to an app")
    app_domain_add.add_argument("app_name")
    app_domain_add.add_argument("domain")
    app_domain_add.add_argument("--no-reload", action="store_true", help="Do not reload nginx")
    app_domain_add.set_defaults(func=cmd_app_domain_add)
    app_domain_remove = app_domain_sub.add_parser("remove", help="Remove an alias domain from an app")
    app_domain_remove.add_argument("app_name")
    app_domain_remove.add_argument("domain")
    app_domain_remove.add_argument("--no-reload", action="store_true", help="Do not reload nginx")
    app_domain_remove.set_defaults(func=cmd_app_domain_remove)
    app_domain_main = app_domain_sub.add_parser("set-main", help="Set the app main domain")
    app_domain_main.add_argument("app_name")
    app_domain_main.add_argument("domain")
    app_domain_main.add_argument("--no-reload", action="store_true", help="Do not reload nginx")
    app_domain_main.set_defaults(func=cmd_app_domain_set_main)
    app_list = app_sub.add_parser("list", help="List apps")
    app_list.set_defaults(func=cmd_app_list)
    app_show = app_sub.add_parser("show", help="Show an app record")
    app_show.add_argument("app_name")
    app_show.set_defaults(func=cmd_app_show)

    user = sub.add_parser("user", help="Deprecated: manage app identities")
    user_sub = user.add_subparsers(dest="user_command", required=True)
    user_create = user_sub.add_parser("create", help="Create/update a PHP-FPM user and pool")
    user_create.add_argument("username")
    user_create.add_argument("uid", nargs="?", type=int)
    user_create.add_argument("--php", default=default_php_version(), help="PHP version")
    user_create.add_argument("--no-mysql", action="store_true", help="Do not create/update the MySQL account")
    user_create.add_argument("--mysql-password", help="Password for the MySQL account")
    user_create.add_argument("--mysql-service", default=default_mysql_service(), help="MySQL service to create the account in, e.g. mysql57/mysql84/mysql97")
    user_create.add_argument("--no-reload", action="store_true", help="Do not reload PHP-FPM")
    user_create.set_defaults(func=cmd_user_create)

    site = sub.add_parser("site", help="Manage PHP sites")
    site_sub = site.add_subparsers(dest="site_command", required=True)
    site_create = site_sub.add_parser("create", help="Create/update a PHP vhost")
    site_create.add_argument("username")
    site_create.add_argument("domain")
    site_create.add_argument("db_name", nargs="?")
    site_create.add_argument("--php", default=default_php_version(), help="PHP version")
    site_create.add_argument("--mysql-service", default=default_mysql_service(), help="MySQL service for optional database creation, e.g. mysql57/mysql84/mysql97")
    site_create.add_argument("--alias", action="append", help="Additional server_name; can be passed multiple times or comma-separated")
    site_create.add_argument("--aliases", help="Comma-separated additional server names")
    site_create.add_argument("--no-index", action="store_true", help="Do not create starter index.php")
    site_create.add_argument("--no-reload", action="store_true", help="Do not reload nginx/PHP-FPM")
    site_create.set_defaults(func=cmd_site_create)

    proxy = sub.add_parser("proxy", help="Manage reverse proxy vhosts")
    proxy_sub = proxy.add_subparsers(dest="proxy_command", required=True)
    proxy_create = proxy_sub.add_parser("create", help="Create/update a proxy vhost")
    proxy_create.add_argument("domain")
    proxy_create.add_argument("upstream")
    proxy_create.add_argument("--alias", action="append", help="Additional server_name; can be passed multiple times or comma-separated")
    proxy_create.add_argument("--aliases", help="Comma-separated additional server names")
    proxy_create.add_argument("--no-reload", action="store_true", help="Do not reload nginx")
    proxy_create.set_defaults(func=cmd_proxy_create)

    cron = sub.add_parser("cron", help="Manage supercronic jobs")
    cron_sub = cron.add_subparsers(dest="cron_command", required=True)
    cron_create = cron_sub.add_parser("create", help="Create/update an app cron job")
    cron_create.add_argument("app_name")
    cron_create.add_argument("job_name")
    cron_create.add_argument("schedule")
    cron_create.add_argument("command")
    cron_create.add_argument("--php", default=default_php_version(), help="PHP version")
    cron_create.add_argument("--workdir", "-w", help="Container workdir")
    cron_create.set_defaults(func=cmd_cron_create)
    cron_reload_cmd = cron_sub.add_parser("reload", help="Rebuild merged crontab and reload Supercronic")
    cron_reload_cmd.add_argument("--php", default=default_php_version(), help="PHP version")
    cron_reload_cmd.set_defaults(func=cmd_cron_reload)

    app_exec = sub.add_parser("exec", help="Run a command in an ephemeral PHP CLI container as an app")
    app_exec.add_argument("app_name")
    app_exec.add_argument("--php", default=default_php_version(), help="PHP version")
    app_exec.add_argument("--workdir", "-w", help="Container workdir")
    app_exec.add_argument("command", nargs=argparse.REMAINDER, help="Command to run; prefix with -- if needed")
    app_exec.set_defaults(func=cmd_app_exec)

    shell = sub.add_parser("shell", help="Open an ephemeral PHP CLI shell as an app; with no args, choose from state")
    shell.add_argument("app_name", nargs="?")
    shell.add_argument("--php", default=default_php_version(), help="PHP version")
    shell.add_argument("--workdir", "-w", help="Container workdir")
    shell.add_argument("--shell", default="bash", help="Shell to run, default: bash")
    shell.set_defaults(func=cmd_app_shell)

    tls = sub.add_parser("tls", help="Manage vhost TLS mode")
    tls_sub = tls.add_subparsers(dest="tls_command", required=True)
    tls_acme = tls_sub.add_parser("acme", help="Enable nginx ACME for a vhost, or switch back to self-signed")
    tls_acme.add_argument("domain")
    tls_acme.add_argument("--off", "--self-signed", action="store_true", help="Switch back to the default self-signed cert")
    tls_acme.add_argument("--no-redirect-https", action="store_true", help="Do not rewrite the HTTP vhost to redirect to HTTPS after enabling ACME")
    tls_acme.add_argument("--no-reload", action="store_true", help="Do not reload nginx")
    tls_acme.set_defaults(func=cmd_tls_acme)
    tls_cert = tls_sub.add_parser("cert", help="Use explicit certificate files for a vhost")
    tls_cert.add_argument("domain")
    tls_cert.add_argument("--cert", "--fullchain")
    tls_cert.add_argument("--key", "--privkey")
    tls_cert.add_argument("--no-reload", action="store_true", help="Do not reload nginx")
    tls_cert.set_defaults(func=cmd_tls_cert)

    compose_cmd = sub.add_parser("compose", help="Run docker compose with VibeOps base plus local override files")
    compose_cmd.add_argument("compose_args", nargs=argparse.REMAINDER, help="Arguments passed to docker compose")
    compose_cmd.set_defaults(func=cmd_compose)

    render = sub.add_parser("render", help="Regenerate disposable runtime config from state")
    render.set_defaults(func=cmd_render)

    apply = sub.add_parser("apply", help="Render config, then validate/reload running services")
    apply.add_argument("--no-reload", action="store_true", help="Only render files; do not reload services")
    apply.set_defaults(func=cmd_apply)

    status = sub.add_parser("status", help="Show stack status dashboard")
    status.add_argument("--check-nginx", action="store_true", help="Run nginx -t when nginx is running")
    status.set_defaults(func=cmd_status)

    wizard = sub.add_parser("wizard", aliases=["tui"], help="Interactive guided menu for common tasks")
    wizard.set_defaults(func=cmd_wizard)

    list_cmd = sub.add_parser("list", help="List metadata from state")
    list_cmd.add_argument("kind", choices=["apps", "domains", "crons", "all", "users", "sites"])
    list_cmd.set_defaults(func=cmd_list)

    state = sub.add_parser("state", help="Inspect/init the JSON metadata DB")
    state_sub = state.add_subparsers(dest="state_action", required=True)
    state_init = state_sub.add_parser("init", help="Create an empty runtime/state/stack.json")
    state_init.add_argument("--force", action="store_true")
    state_init.set_defaults(func=cmd_state)
    state_path = state_sub.add_parser("path", help="Print metadata DB path")
    state_path.set_defaults(func=cmd_state)
    state_show = state_sub.add_parser("show", help="Print metadata DB JSON")
    state_show.set_defaults(func=cmd_state)
    state_migrate = state_sub.add_parser("migrate", help="Move/upgrade legacy ./stack.json into runtime/state/stack.json")
    state_migrate.add_argument("--force", action="store_true")
    state_migrate.set_defaults(func=cmd_state)

    return parser


def main(argv: list[str] | None = None) -> int:
    if argv is None:
        argv = sys.argv[1:]
    if not argv and sys.stdin.isatty():
        argv = ["wizard"]
    parser = build_parser()
    args = parser.parse_args(argv)
    if args.func is None:
        parser.print_help()
        return 2
    try:
        args.func(args)
        return 0
    except StackError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    except subprocess.CalledProcessError as exc:
        print(f"error: command failed ({exc.returncode}): {' '.join(exc.cmd)}", file=sys.stderr)
        if exc.stderr:
            print(exc.stderr, file=sys.stderr)
        return exc.returncode or 1


if __name__ == "__main__":
    raise SystemExit(main())
