"""Shared constants and helpers for VibeOps command modules."""
from __future__ import annotations

import argparse
import datetime as _dt
import fcntl
import json
import os
import re
import secrets
import shlex
import shutil
import subprocess
import sys
import tempfile
from contextlib import contextmanager
from functools import wraps
from pathlib import Path, PurePosixPath
from typing import Any, Iterable, Iterator
from zoneinfo import ZoneInfo, ZoneInfoNotFoundError

from vibeops.template import render_template_text as render_vibeops_template_text

ROOT = Path(__file__).resolve().parents[1]
CONFIG_DIR = ROOT / "config"
RUNTIME_DIR = ROOT / "runtime"
STATE_DIR = RUNTIME_DIR / "state"
DB_PATH = STATE_DIR / "stack.json"
LEGACY_DB_PATH = ROOT / "stack.json"
GENERATED_DIR = RUNTIME_DIR / "generated"
CUSTOM_DIR = RUNTIME_DIR / "custom"
HOME_DIR = RUNTIME_DIR / "home"
PHP_CONFIG_DIR = CONFIG_DIR / "php"
PHP_GENERATED_DIR = GENERATED_DIR / "php"
PHP_VERSIONS_DIR = PHP_GENERATED_DIR / "versions"
LEGACY_PHP_VERSIONS_DIR = PHP_CONFIG_DIR / "versions"
PHP_TEMPLATE_DIR = PHP_CONFIG_DIR / "templates"
MYSQL_TEMPLATE_DIR = CONFIG_DIR / "mysql" / "templates"
MYSQL_SECRETS_DIR = RUNTIME_DIR / "secrets" / "mysql"
NGINX_TEMPLATE_DIR = CONFIG_DIR / "nginx" / "templates"
NGINX_VHOST_DIR = GENERATED_DIR / "nginx" / "vhosts"
CERTS_DIR = RUNTIME_DIR / "certs"
PHP_SOCKET_DIR = RUNTIME_DIR / "run" / "php-fpm"
PHP_LOG_DIR = RUNTIME_DIR / "logs" / "php"
CRON_RUNTIME_DIR = GENERATED_DIR / "cron"
SCHEMA_VERSION = 5
DOCROOT_NAME = "www"
GENERATED_NOTICE = "GENERATED BY VIBEOPS. Do not edit directly; update runtime/state/stack.json and run ./manage.py render."
GENERATED_HEADER = f"# {GENERATED_NOTICE}\n"
PHP_FPM_GENERATED_HEADER = f"; {GENERATED_NOTICE}\n"

APP_NAME_RE = re.compile(r"^[a-z_][a-z0-9_-]{0,31}$")
USERNAME_RE = APP_NAME_RE
DOMAIN_RE = re.compile(r"^[A-Za-z0-9.-]+$")
DOMAIN_PATH_RE = re.compile(r"^[A-Za-z0-9._-]+$")
PHP_VERSION_RE = re.compile(r"^[0-9]+\.[0-9]+$")
DB_NAME_RE = re.compile(r"^[A-Za-z0-9_]+$")
PUBLIC_DIR_RE = re.compile(r"^[A-Za-z0-9._/-]*$")
PHP_ENTRYPOINTS = {"front-controller", "legacy"}
MYSQL_SERVICE_RE = re.compile(r"^mysql[0-9]+$")
JOB_RE = re.compile(r"^[A-Za-z0-9_.-]+$")
CRON_LOCK_RE = JOB_RE


class StackError(RuntimeError):
    pass


def now() -> str:
    return _dt.datetime.now(_dt.timezone.utc).replace(microsecond=0).isoformat()


def rel(path: Path | str) -> str:
    p = Path(path)
    try:
        return str(p.resolve().relative_to(ROOT))
    except Exception:
        return str(p)


def info(message: str) -> None:
    print(message)


def warn(message: str) -> None:
    print(f"Warning: {message}", file=sys.stderr)


def die(message: str) -> None:
    raise StackError(message)


def validate(value: str, pattern: re.Pattern[str], label: str) -> str:
    if not value or not pattern.match(value):
        die(f"Invalid {label}: {value}")
    return value


def parse_env_file(path: Path) -> dict[str, str]:
    env: dict[str, str] = {}
    if not path.exists():
        return env
    for raw in path.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key:
            env[key] = value
    return env


def stack_env() -> dict[str, str]:
    env = parse_env_file(ROOT / ".env")
    merged = dict(env)
    merged.update(os.environ)
    return merged


def default_php_version() -> str:
    return stack_env().get("DEFAULT_PHP_VERSION", "8.4")


def default_mysql_service() -> str:
    return stack_env().get("DEFAULT_MYSQL_SERVICE", "mysql84")


def mysql_root_password(env: dict[str, str], service: str) -> str | None:
    return env.get(f"{service.upper()}_ROOT_PASSWORD") or env.get("MYSQL_ROOT_PASSWORD")


def mysql_root_option_file(service: str) -> Path:
    service = validate(service, MYSQL_SERVICE_RE, "MySQL service")
    return MYSQL_SECRETS_DIR / f"{service}-root.cnf"


def render_mysql_root_option_files() -> list[Path]:
    """Write root client option files for local container administration."""
    env = stack_env()
    rendered: list[Path] = []
    for service in ("mysql57", "mysql84", "mysql97"):
        password = mysql_root_password(env, service)
        if not password:
            continue
        # MySQL option files accept quoted values; escape their two special chars.
        escaped = password.replace("\\", "\\\\").replace('"', '\\"')
        path = mysql_root_option_file(service)
        write_text_atomic(path, f'[client]\nuser=root\npassword="{escaped}"\nprotocol=socket\n', 0o600)
        rendered.append(path)
    return rendered


def php_service_for(version: str) -> str:
    return "php" + version.replace(".", "")


def php_cron_service_for(version: str) -> str:
    return php_service_for(version) + "-cron"


def php_cli_service_for(version: str) -> str:
    return php_service_for(version) + "-cli"


def php_version_config_dir(version: str) -> Path:
    return PHP_VERSIONS_DIR / version


def cron_dir_for(version: str) -> Path:
    return CRON_RUNTIME_DIR / php_service_for(version)


def cron_jobs_dir_for(version: str) -> Path:
    return cron_dir_for(version) / "jobs"


def empty_db() -> dict[str, Any]:
    return {
        "schema": SCHEMA_VERSION,
        "defaults": {
            "php_version": default_php_version(),
            "mysql_service": default_mysql_service(),
        },
        "apps": {},
        "domains": {},
        "sites": {},
        "users": {},
        "crons": {},
        "updated_at": now(),
    }


def state_path() -> Path:
    if DB_PATH.exists():
        return DB_PATH
    if LEGACY_DB_PATH.exists():
        warn(f"using legacy state at {rel(LEGACY_DB_PATH)}; run './manage.py state migrate' to move it to {rel(DB_PATH)}")
        return LEGACY_DB_PATH
    return DB_PATH


def normalize_db(data: dict[str, Any]) -> dict[str, Any]:
    schema = int(data.get("schema", 0) or 0)
    if schema > SCHEMA_VERSION:
        die(f"state schema is {schema}; this CLI expects schema {SCHEMA_VERSION}")
    data["schema"] = SCHEMA_VERSION
    data.setdefault("defaults", {})
    data["defaults"].setdefault("php_version", default_php_version())
    data["defaults"].setdefault("mysql_service", default_mysql_service())
    data.setdefault("apps", {})
    data.setdefault("domains", {})
    data.setdefault("sites", {})
    data.setdefault("users", {})
    data.setdefault("crons", {})
    for app_name, app in data.get("apps", {}).items():
        if isinstance(app, dict):
            app.setdefault("name", app_name)
            public_dir = validate_public_dir(str(app.get("public_dir", "")))
            app["public_dir"] = public_dir
            app.setdefault("php_entrypoint", default_php_entrypoint(public_dir))
            app["php_entrypoint"] = validate_php_entrypoint(str(app.get("php_entrypoint") or "auto"), public_dir)
            if app.get("vhost"):
                app["vhost"] = rel(app_vhost_path(app_name))
    for domain, site in data.get("sites", {}).items():
        if isinstance(site, dict) and site.get("type") == "proxy":
            site.setdefault("domain", domain)
            site["vhost"] = rel(NGINX_VHOST_DIR / f"{domain}.conf")
    return data


def load_db() -> dict[str, Any]:
    path = state_path()
    if not path.exists():
        return empty_db()
    try:
        data = json.loads(path.read_text())
    except json.JSONDecodeError as exc:
        die(f"Cannot parse {rel(path)}: {exc}")
    if not isinstance(data, dict):
        die(f"{rel(path)} must contain a JSON object")
    return normalize_db(data)


def save_db(data: dict[str, Any]) -> None:
    normalize_db(data)
    data["schema"] = SCHEMA_VERSION
    data["updated_at"] = now()
    text = json.dumps(data, indent=2, sort_keys=True) + "\n"
    mkdir(DB_PATH.parent)
    fd, tmp_name = tempfile.mkstemp(prefix=".stack.", suffix=".json", dir=str(DB_PATH.parent))
    try:
        with os.fdopen(fd, "w") as fh:
            fh.write(text)
        os.replace(tmp_name, DB_PATH)
    finally:
        if os.path.exists(tmp_name):
            os.unlink(tmp_name)


def upsert_timestamp(item: dict[str, Any]) -> None:
    item.setdefault("created_at", now())
    item["updated_at"] = now()


def mkdir(path: Path, mode: int | None = None) -> None:
    path.mkdir(parents=True, exist_ok=True)
    if mode is not None:
        try:
            path.chmod(mode)
        except PermissionError:
            warn(f"could not chmod {rel(path)}")


def write_text(path: Path, content: str, mode: int | None = None) -> None:
    mkdir(path.parent)
    path.write_text(content)
    if mode is not None:
        try:
            path.chmod(mode)
        except PermissionError:
            warn(f"could not chmod {rel(path)}")


def write_text_atomic(path: Path, content: str, mode: int = 0o644) -> None:
    """Atomically replace generated runtime config visible to containers."""
    mkdir(path.parent)
    fd, tmp_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=str(path.parent))
    try:
        with os.fdopen(fd, "w") as fh:
            fh.write(content)
            fh.flush()
            os.fsync(fh.fileno())
        os.chmod(tmp_name, mode)
        os.replace(tmp_name, path)
    finally:
        if os.path.exists(tmp_name):
            os.unlink(tmp_name)


@contextmanager
def cron_state_lock() -> Iterator[None]:
    """Serialize cron state/render/reload mutations from concurrent manage.py calls."""
    lock_path = STATE_DIR / ".cron.lock"
    mkdir(lock_path.parent)
    with lock_path.open("a+") as lock:
        fcntl.flock(lock.fileno(), fcntl.LOCK_EX)
        try:
            yield
        finally:
            fcntl.flock(lock.fileno(), fcntl.LOCK_UN)


def serialized_cron_state(func: Any) -> Any:
    """Decorator for render/apply operations that also replace cron artifacts."""
    @wraps(func)
    def wrapped(*args: Any, **kwargs: Any) -> Any:
        with cron_state_lock():
            return func(*args, **kwargs)
    return wrapped


def validate_cron_workdir(app_name: str, workdir: str) -> str:
    root = PurePosixPath("/home") / app_name
    path = PurePosixPath(workdir)
    if not path.is_absolute() or ".." in path.parts or path != root and root not in path.parents:
        die(f"Cron workdir must stay inside {root}: {workdir}")
    return str(path)


def validate_timezone(value: str) -> str:
    try:
        ZoneInfo(value)
    except (ZoneInfoNotFoundError, ValueError):
        die(f"Invalid timezone: {value}")
    return value


def render_template_text(text: str, values: dict[str, Any]) -> str:
    return render_vibeops_template_text(text, values)


def template_text(path: Path, values: dict[str, Any]) -> str:
    if not path.exists():
        die(f"Missing template: vibeops/{rel(path)}")
    return render_template_text(path.read_text(), values)


def generated_header_for(path: Path) -> str:
    # PHP 8.5's FPM INI parser rejects leading '#' comments in pool files.
    # Use ';' only for generated php-fpm pool fragments; keep '#' for nginx,
    # shell env, SQL, and cron files.
    try:
        path.resolve().relative_to(PHP_VERSIONS_DIR.resolve())
    except ValueError:
        return GENERATED_HEADER
    return PHP_FPM_GENERATED_HEADER if path.parent.name == "pool.d" and path.suffix == ".conf" else GENERATED_HEADER


def write_template(path: Path, template: Path, values: dict[str, Any], mode: int | None = None, *, generated: bool = False) -> None:
    content = template_text(template, values)
    if generated:
        content = generated_header_for(path) + content
    write_text(path, content, mode)


def mysql_string_literal(value: str) -> str:
    return value.replace("\\", "\\\\").replace("'", "''")


def mysql_grant_pattern(value: str) -> str:
    """Escape MySQL GRANT database-pattern wildcards for a literal identifier fragment."""
    return value.replace("\\", "\\\\").replace("_", "\\_").replace("%", "\\%")


def mysql_user_database_grant_pattern(username: str) -> str:
    """Return the database pattern for all databases owned by username: <username>_*.

    In MySQL GRANT database patterns, ``_`` and ``%`` are wildcards even inside the
    database pattern. Escape username wildcards and append an escaped separator
    underscore so ``foo_bar`` grants ``foo_bar_*``, not ``fooXbar_*``.
    """
    return mysql_grant_pattern(username) + r"\_%"


def mysql_backup_dir(service: str) -> Path:
    service = validate(service, MYSQL_SERVICE_RE, "MySQL service")
    return RUNTIME_DIR / "backups" / service


def mysql_log_dir(service: str) -> Path:
    service = validate(service, MYSQL_SERVICE_RE, "MySQL service")
    return RUNTIME_DIR / "logs" / service


SYSTEM_MYSQL_DATABASES = frozenset({"mysql", "sys", "performance_schema", "information_schema"})


def mysql_root_exec_sql(sql: str, *, service: str | None = None, check: bool = True) -> subprocess.CompletedProcess[str]:
    """Run SQL as MySQL root using the protected client option file."""
    service = validate(service or default_mysql_service(), MYSQL_SERVICE_RE, "MySQL service")
    if not service_running(service):
        die(f"{service} service is not running")
    cp = run(
        [
            "docker", "compose", "exec", "-T", service,
            "sh", "-lc",
            'mysql --defaults-extra-file=/run/secrets/vibeops-root.cnf --batch --raw',
        ],
        input_text=sql,
        check=False,
        capture=True,
    )
    if check and cp.returncode != 0:
        err = (cp.stderr or cp.stdout or "").strip()
        # Avoid echoing secrets; mysql may warn about CLI password usage inside the container.
        die(f"mysql on {service} failed (exit {cp.returncode})" + (f": {err}" if err else ""))
    return cp


def mysql_admin_ping(service: str | None = None) -> bool:
    service = validate(service or default_mysql_service(), MYSQL_SERVICE_RE, "MySQL service")
    if not service_running(service):
        return False
    cp = run(
        [
            "docker", "compose", "exec", "-T", service,
            "sh", "-lc",
            'mysqladmin --defaults-extra-file=/run/secrets/vibeops-root.cnf ping --silent',
        ],
        check=False,
        capture=True,
    )
    return cp.returncode == 0


def command_exists(name: str) -> bool:
    return shutil.which(name) is not None


def run(cmd: list[str], *, input_text: str | None = None, check: bool = True, capture: bool = False) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        cmd,
        cwd=str(ROOT),
        input=input_text,
        text=True,
        check=check,
        stdout=subprocess.PIPE if capture else None,
        stderr=subprocess.PIPE if capture else None,
    )


def docker_available() -> bool:
    return command_exists("docker")


def running_services() -> set[str]:
    if not docker_available():
        return set()
    cp = run(
        ["docker", "compose", "ps", "--services", "--filter", "status=running"],
        check=False,
        capture=True,
    )
    if cp.returncode != 0:
        return set()
    return {line.strip() for line in cp.stdout.splitlines() if line.strip()}


def service_running(service: str) -> bool:
    return service in running_services()


def nginx_reload(no_reload: bool = False) -> None:
    if no_reload:
        return
    if service_running("nginx"):
        run(["docker", "compose", "exec", "-T", "nginx", "nginx", "-t"])
        run(["docker", "compose", "exec", "-T", "nginx", "nginx", "-s", "reload"])
        info("Reloaded nginx")
    else:
        info("nginx container is not running; start it then run: docker compose exec nginx nginx -t && docker compose exec nginx nginx -s reload")


def php_reload(service: str, username: str, no_reload: bool = False) -> None:
    if service_running(service):
        run(["docker", "compose", "exec", "-T", service, "php-identity-sync", username])
        if not no_reload:
            try:
                # php-fpm -tt writes its full configuration dump to stderr even
                # when validation succeeds. Keep app creation output concise.
                run(["docker", "compose", "exec", "-T", service, "php-fpm", "-tt"], capture=True)
                run([
                    "docker", "compose", "exec", "-T", service, "sh", "-lc",
                    "kill -USR2 1",
                ], capture=True)
            except subprocess.CalledProcessError:
                die(f"Failed to validate or reload {service}")
            info(f"Reloaded {service}")
    else:
        info(f"{service} is not running; run/restart it to create the Linux user inside that PHP container.")


def rebuild_supercronic_crontab(php_version: str) -> Path:
    cron_dir = cron_dir_for(php_version)
    mkdir(cron_dir)
    combined = cron_dir / ".supercronic.cron"
    logrotate_config = cron_dir / ".logrotate.conf"
    php_cron_service = php_cron_service_for(php_version)
    write_text_atomic(logrotate_config, f"""/home/*/logs/cron-{php_cron_service}-*.log /home/*/logs/fpm-php-{php_version}.error.log /home/*/logs/fpm-php-{php_version}.slow.log {{
    daily
    rotate 14
    dateext
    dateformat -%Y-%m-%d
    compress
    delaycompress
    missingok
    notifempty
    copytruncate
    su root root
}}
""")
    job_files = sorted(cron_jobs_dir_for(php_version).glob("*.cron"))
    lines = [
        "SHELL=/bin/sh",
        "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
        "",
        "# Always rotate app-owned cron output and FPM logs into dated archives.",
        f"17 3 * * * /usr/sbin/logrotate -s /var/lib/logrotate/vibeops-{php_cron_service}.status /usr/local/etc/php/cron.d/.logrotate.conf",
        "",
    ]
    for cron_file in job_files:
        lines.append(f"# /usr/local/etc/php/cron.d/{cron_file.name}")
        lines.append(cron_file.read_text().rstrip("\n"))
        lines.append("")
    write_text_atomic(combined, "\n".join(lines) + "\n")
    return combined


def cron_reload(service: str, usernames: Iterable[str] = ()) -> None:
    crontab = "/usr/local/etc/php/cron.d/.supercronic.cron"
    if service_running(service):
        run(["docker", "compose", "exec", "-T", service, "php-identity-sync", *usernames])
        run(["docker", "compose", "exec", "-T", service, "supercronic", "-test", crontab])
        run(["docker", "compose", "kill", "-s", "USR2", service])
        info(f"Validated and reloaded {service} cron with SIGUSR2")
        return

    # The matching FPM image has the same binary and read-only cron mount, so it
    # can still provide authoritative validation while the scheduler is stopped.
    php_service = service.removesuffix("-cron")
    if service_running(php_service):
        run(["docker", "compose", "exec", "-T", php_service, "supercronic", "-test", crontab])
        info(f"Validated {service} crontab using {php_service}")
    else:
        warn(f"could not run supercronic -test because {service} and {php_service} are stopped; scheduler startup will validate it")
    info(f"{service} is not running; start it to load this cron job.")


def read_uid_from_env(path: Path) -> int | None:
    try:
        for line in path.read_text().splitlines():
            if line.startswith("UID="):
                return int(line.split("=", 1)[1])
    except Exception:
        return None
    return None


def allocate_uid(app_name: str, explicit_uid: int | None, db: dict[str, Any]) -> int:
    if explicit_uid is not None:
        return explicit_uid

    existing = db.get("apps", {}).get(app_name, {}).get("uid")
    if isinstance(existing, int):
        return existing

    for base in (PHP_VERSIONS_DIR, LEGACY_PHP_VERSIONS_DIR):
        for path in sorted(base.glob(f"*/users.d/{app_name}.env")):
            uid = read_uid_from_env(path)
            if uid is not None:
                return uid

    max_uid = 0
    for app in db.get("apps", {}).values():
        uid = app.get("uid") if isinstance(app, dict) else None
        if isinstance(uid, int):
            max_uid = max(max_uid, uid)
    for base in (PHP_VERSIONS_DIR, LEGACY_PHP_VERSIONS_DIR):
        for path in base.glob("*/users.d/*.env"):
            uid = read_uid_from_env(path)
            if uid is not None:
                max_uid = max(max_uid, uid)
    return 10000 if max_uid < 10000 else max_uid + 1


def generate_password(length: int = 20) -> str:
    alphabet = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
    return "".join(secrets.choice(alphabet) for _ in range(length))


def create_mysql_user(username: str, password: str | None, mysql_service: str) -> tuple[bool, str | None]:
    env = stack_env()
    mysql_service = validate(mysql_service, MYSQL_SERVICE_RE, "MySQL service")
    if not (ROOT / ".env").exists() or not service_running(mysql_service):
        info(f"Skipped MySQL user creation; start {mysql_service} and rerun, or pass --no-mysql.")
        return False, None
    if not mysql_root_password(env, mysql_service):
        info(f"Skipped MySQL user creation; {mysql_service.upper()}_ROOT_PASSWORD or MYSQL_ROOT_PASSWORD is missing.")
        return False, None

    cred_dir = HOME_DIR / username / ".credentials"
    cred_path = cred_dir / f"{mysql_service}.env"
    existing_password = parse_env_file(cred_path).get("MYSQL_PASSWORD") if cred_path.exists() else None
    password = password or env.get(f"{mysql_service.upper()}_USER_PASSWORD") or env.get("MYSQL_USER_PASSWORD") or existing_password or generate_password()
    mkdir(cred_dir, 0o700)
    write_template(cred_path, MYSQL_TEMPLATE_DIR / "user-credentials.env.template", {
        "USERNAME": username,
        "MYSQL_SERVICE": mysql_service,
        "MYSQL_PASSWORD": password,
    }, 0o600)

    sql = template_text(MYSQL_TEMPLATE_DIR / "create-user.sql.template", {
        "USERNAME": username,
        "MYSQL_PASSWORD_SQL": mysql_string_literal(password),
        "DB_GRANT_PATTERN": mysql_user_database_grant_pattern(username),
    })
    mysql_root_exec_sql(sql, service=mysql_service)
    info(f"MySQL account ready on {mysql_service}: user={username}")
    info(f"Credentials saved (mode 600): vibeops/{rel(cred_path)}")
    info("Password is only in that file; not printed here.")
    return True, rel(cred_path)



def app_home(app_name: str) -> Path:
    return HOME_DIR / app_name


def app_www(app_name: str) -> Path:
    return app_home(app_name) / DOCROOT_NAME


def validate_public_dir(public_dir: str | None) -> str:
    public_dir = (public_dir or "").strip().strip("/")
    if public_dir in {".", ".."} or public_dir.startswith("../") or "/../" in public_dir or public_dir.endswith("/.."):
        die(f"Invalid public_dir: {public_dir}")
    if not PUBLIC_DIR_RE.match(public_dir):
        die(f"Invalid public_dir: {public_dir}")
    return public_dir


def default_php_entrypoint(public_dir: str | None) -> str:
    return "front-controller" if validate_public_dir(public_dir) else "legacy"


def validate_php_entrypoint(value: str | None, public_dir: str | None = "") -> str:
    value = (value or "auto").strip().lower().replace("_", "-")
    if value in {"auto", ""}:
        return default_php_entrypoint(public_dir)
    if value in {"front", "frontcontroller", "index", "index-only", "single-index"}:
        value = "front-controller"
    if value in {"direct", "classic", "old", "old-way"}:
        value = "legacy"
    if value not in PHP_ENTRYPOINTS:
        die(f"Invalid PHP entrypoint: {value} (expected auto, front-controller, or legacy)")
    return value


def app_document_root(app_name: str, public_dir: str | None = "") -> Path:
    public_dir = validate_public_dir(public_dir)
    return app_www(app_name) / public_dir if public_dir else app_www(app_name)


def container_document_root(app_name: str, public_dir: str | None = "") -> str:
    public_dir = validate_public_dir(public_dir)
    base = f"/home/{app_name}/{DOCROOT_NAME}"
    return f"{base}/{public_dir}" if public_dir else base


def app_vhost_path(app_name: str) -> Path:
    return NGINX_VHOST_DIR / f"app-{app_name}.conf"


def render_template(template: Path, destination: Path, values: dict[str, Any]) -> None:
    write_template(destination, template, values, generated=True)


def normalize_aliases(alias: Iterable[str] | None, aliases: str | None) -> list[str]:
    out: list[str] = []
    for value in alias or []:
        for item in value.split(","):
            item = item.strip()
            if item:
                out.append(validate(item, DOMAIN_RE, "alias domain"))
    if aliases:
        for item in aliases.split(","):
            item = item.strip()
            if item:
                out.append(validate(item, DOMAIN_RE, "alias domain"))
    return sorted(dict.fromkeys(out))


def domains_for(main_domain: str, aliases: Iterable[str]) -> list[str]:
    ordered = [main_domain, *aliases]
    return list(dict.fromkeys(ordered))


def assert_domain_free(domain: str, db: dict[str, Any], *, allow_app: str | None = None, allow_domain: str | None = None) -> None:
    owner = db.get("domains", {}).get(domain)
    if not owner:
        return
    if owner.get("kind") == "php" and allow_app and owner.get("app") == allow_app:
        return
    if owner.get("kind") == "proxy" and allow_domain and owner.get("domain") == allow_domain:
        return
    die(f"Domain already exists in stack.json: {domain} ({owner.get('kind')})")


def apply_app_mysql_metadata(app: dict[str, Any], app_name: str, mysql_service: str, credential_path: str | None = None) -> None:
    app["mysql_service"] = mysql_service
    app["mysql_host"] = mysql_service
    app["mysql_port"] = 3306
    app["mysql_user_name"] = app_name
    if credential_path:
        app["mysql_credentials"] = credential_path


def require_mysql_ready_for_sql(service: str) -> str:
    """Fail unless the MySQL service can accept root SQL administration.

    Checks running state, root password configuration, and the protected client
    option file. Does not start services or mutate Docker state.
    """
    service = validate(service, MYSQL_SERVICE_RE, "MySQL service")
    env = stack_env()
    if not (ROOT / ".env").exists() or not service_running(service) or not mysql_root_password(env, service):
        die(f"Cannot create database; {service} is not running, .env is missing, or root password is unset.")
    option_file = mysql_root_option_file(service)
    if not option_file.is_file():
        die(f"Missing protected MySQL option file vibeops/{rel(option_file)}; run ./manage.py render")
    return service


def ensure_mysql_database(app_name: str, suffix: str, mysql_service: str) -> str:
    """Create DB app_name_suffix and grant <app_name>_* privileges. Returns full name only after SQL succeeds."""
    mysql_service = require_mysql_ready_for_sql(mysql_service)
    app_name = validate(app_name, APP_NAME_RE, "app_name")
    validate(suffix, DB_NAME_RE, "database suffix")
    db_full_name = f"{app_name}_{suffix}"
    sql = template_text(MYSQL_TEMPLATE_DIR / "create-database.sql.template", {
        "DB_FULL_NAME": db_full_name,
        "USERNAME": app_name,
        "DB_GRANT_PATTERN": mysql_user_database_grant_pattern(app_name),
    })
    mysql_root_exec_sql(sql, service=mysql_service)
    info(f"MySQL database on {mysql_service}: {db_full_name}")
    return db_full_name


def ensure_app_identity(app_name: str, php_version: str, db: dict[str, Any], *, uid: int | None = None, public_dir: str | None = None, no_mysql: bool = False, mysql_password: str | None = None, mysql_service: str | None = None, no_reload: bool = False) -> dict[str, Any]:
    app_name = validate(app_name, APP_NAME_RE, "app_name")
    php_version = validate(php_version, PHP_VERSION_RE, "PHP version")
    mysql_service = validate(mysql_service or default_mysql_service(), MYSQL_SERVICE_RE, "MySQL service")
    app_uid = allocate_uid(app_name, uid, db)
    php_service = php_service_for(php_version)
    socket_group_name = stack_env().get("SOCKET_GROUP_NAME", "nginxsock")
    app = db["apps"].setdefault(app_name, {"name": app_name})
    public_dir = validate_public_dir(public_dir if public_dir is not None else str(app.get("public_dir", "")))
    app["uid"] = app_uid
    app["public_dir"] = public_dir
    app["php_entrypoint"] = validate_php_entrypoint(str(app.get("php_entrypoint") or "auto"), public_dir)
    app["php_version"] = php_version
    app["php_service"] = php_service

    mkdir(app_home(app_name) / "logs", 0o770)
    mkdir(app_www(app_name))
    mkdir(app_home(app_name) / ".credentials", 0o700)
    mkdir(app_home(app_name) / ".composer")
    mkdir(app_home(app_name) / ".ssh", 0o700)
    mkdir(php_version_config_dir(php_version) / "users.d")
    mkdir(php_version_config_dir(php_version) / "pool.d")
    mkdir(cron_dir_for(php_version))
    mkdir(PHP_SOCKET_DIR / php_service)
    mkdir(PHP_LOG_DIR / php_service)

    fallback_path = php_version_config_dir(php_version) / "pool.d" / "zz-fallback.conf"
    if not fallback_path.exists():
        write_template(fallback_path, PHP_TEMPLATE_DIR / "fallback.conf.template", {"SOCKET_GROUP_NAME": socket_group_name}, generated=True)

    write_template(php_version_config_dir(php_version) / "users.d" / f"{app_name}.env", PHP_TEMPLATE_DIR / "user.env.template", {
        "USERNAME": app_name,
        "UID": app_uid,
        "GID": app_uid,
        "PUBLIC_DIR": public_dir,
    }, generated=True)
    write_template(php_version_config_dir(php_version) / "pool.d" / f"{app_name}.conf", PHP_TEMPLATE_DIR / "pool.conf.template", {
        "USERNAME": app_name,
        "SOCKET_GROUP_NAME": socket_group_name,
        "PHP_VERSION": php_version,
    }, generated=True)
    info(f"Created PHP {php_version} app identity: {app_name} uid={app_uid}")
    info(f"Home: vibeops/{rel(app_home(app_name))}")
    info(f"Pool: vibeops/{rel(php_version_config_dir(php_version) / 'pool.d' / f'{app_name}.conf')}")
    info(f"Socket: vibeops/{rel(PHP_SOCKET_DIR / php_service / f'{app_name}.sock')}")

    php_reload(php_service, app_name, no_reload=no_reload)

    mysql_created = False
    credential_path = None
    if not no_mysql:
        mysql_created, credential_path = create_mysql_user(app_name, mysql_password, mysql_service)

    app["home"] = rel(app_home(app_name))
    app["root"] = rel(app_document_root(app_name, public_dir))
    versions = set(app.get("php_versions", []))
    versions.add(php_version)
    app["php_versions"] = sorted(versions)
    app.setdefault("databases", [])
    app.setdefault("tls", {"mode": "self-signed"})
    apply_app_mysql_metadata(app, app_name, mysql_service, credential_path)
    if mysql_created:
        app["mysql_user"] = True
    upsert_timestamp(app)
    return app


def tls_replacement(tls: dict[str, Any] | None) -> str:
    tls = tls or {"mode": "self-signed"}
    mode = tls.get("mode", "self-signed")
    if mode == "acme":
        return template_text(NGINX_TEMPLATE_DIR / "tls-acme.conf.template", {})
    if mode == "files":
        return template_text(NGINX_TEMPLATE_DIR / "tls-files.conf.template", {
            "CERT_PATH": tls.get("cert", ""),
            "CERT_KEY_PATH": tls.get("key", ""),
        })
    return template_text(NGINX_TEMPLATE_DIR / "tls-self-signed.conf.template", {})


def apply_vhost_tls(conf_path: Path, record: dict[str, Any]) -> None:
    tls = record.get("tls") if isinstance(record.get("tls"), dict) else {"mode": "self-signed"}
    replace_tls_block(conf_path, tls_replacement(tls))
    set_https_redirect(conf_path, bool(tls.get("redirect_https")) and tls.get("mode") in {"acme", "files"}, quiet=True)


def replace_tls_block(conf_path: Path, replacement: str) -> None:
    text = conf_path.read_text()
    text2, count = re.subn(r"# BEGIN TLS_CERTIFICATE\n.*?\n\s*# END TLS_CERTIFICATE", lambda _: replacement, text, count=1, flags=re.S)
    if count != 1:
        die(f"Could not find marked TLS certificate block in {rel(conf_path)}")
    write_text(conf_path, text2)


def set_https_redirect(conf_path: Path, enabled: bool, *, quiet: bool = False) -> None:
    """Toggle the generated HTTP vhost redirect flag."""
    text = conf_path.read_text()
    value = "1" if enabled else "0"

    if "set $enable_https_redirect" in text:
        text2, count = re.subn(r"set \$enable_https_redirect [01];", f"set $enable_https_redirect {value};", text, count=1)
    else:
        listen_pos = text.find("listen 80;")
        server_name_pos = text.find("server_name ", listen_pos)
        insert_pos = text.find(";", server_name_pos) + 1 if server_name_pos >= 0 else 0
        if listen_pos < 0 or server_name_pos < 0 or insert_pos <= 0:
            warn(f"Could not find generated HTTP server in {rel(conf_path)}; skipped HTTPS redirect toggle")
            return
        text2 = text[:insert_pos] + f"\n\n    set $enable_https_redirect {value};" + text[insert_pos:]
        count = 1

    if count and text2 != text:
        write_text(conf_path, text2)
        if not quiet:
            info(("Enabled" if enabled else "Disabled") + f" HTTP to HTTPS redirect in vibeops/{rel(conf_path)}")


def render_php_fallback(php_version: str) -> Path:
    php_version = validate(php_version, PHP_VERSION_RE, "PHP version")
    socket_group_name = stack_env().get("SOCKET_GROUP_NAME", "nginxsock")
    mkdir(php_version_config_dir(php_version) / "pool.d")
    fallback_path = php_version_config_dir(php_version) / "pool.d" / "zz-fallback.conf"
    write_template(fallback_path, PHP_TEMPLATE_DIR / "fallback.conf.template", {"SOCKET_GROUP_NAME": socket_group_name}, generated=True)
    return fallback_path


def render_app_identity(app: dict[str, Any]) -> None:
    app_name = validate(str(app.get("name", "")), APP_NAME_RE, "app_name")
    php_version = validate(str(app.get("php_version") or default_php_version()), PHP_VERSION_RE, "PHP version")
    php_service = php_service_for(php_version)
    uid = int(app.get("uid") or read_uid_from_env(php_version_config_dir(php_version) / "users.d" / f"{app_name}.env") or read_uid_from_env(LEGACY_PHP_VERSIONS_DIR / php_version / "users.d" / f"{app_name}.env") or allocate_uid(app_name, None, {"apps": {app_name: app}}))
    socket_group_name = stack_env().get("SOCKET_GROUP_NAME", "nginxsock")
    mkdir(php_version_config_dir(php_version) / "users.d")
    mkdir(php_version_config_dir(php_version) / "pool.d")
    mkdir(PHP_SOCKET_DIR / php_service)
    mkdir(PHP_LOG_DIR / php_service)
    render_php_fallback(php_version)
    public_dir = validate_public_dir(str(app.get("public_dir", "")))
    write_template(php_version_config_dir(php_version) / "users.d" / f"{app_name}.env", PHP_TEMPLATE_DIR / "user.env.template", {
        "USERNAME": app_name,
        "UID": uid,
        "GID": uid,
        "PUBLIC_DIR": public_dir,
    }, generated=True)
    write_template(php_version_config_dir(php_version) / "pool.d" / f"{app_name}.conf", PHP_TEMPLATE_DIR / "pool.conf.template", {
        "USERNAME": app_name,
        "SOCKET_GROUP_NAME": socket_group_name,
        "PHP_VERSION": php_version,
    }, generated=True)
    app["uid"] = uid
    app["php_service"] = php_service
    app["home"] = rel(app_home(app_name))
    app["public_dir"] = public_dir
    app["php_entrypoint"] = validate_php_entrypoint(str(app.get("php_entrypoint") or "auto"), public_dir)
    app["root"] = rel(app_document_root(app_name, public_dir))


def render_app_vhost(app: dict[str, Any]) -> Path:
    app_name = str(app["name"])
    domains = [str(d) for d in (app.get("domains") or [app.get("main_domain")]) if d]
    server_names = " ".join(domains)
    conf_path = app_vhost_path(app_name)
    public_dir = validate_public_dir(str(app.get("public_dir", "")))
    php_service = app.get("php_service") or php_service_for(str(app.get("php_version") or default_php_version()))
    php_entrypoint = validate_php_entrypoint(str(app.get("php_entrypoint") or "auto"), public_dir)
    app["php_entrypoint"] = php_entrypoint
    render_template(NGINX_TEMPLATE_DIR / "site.conf.template", conf_path, {
        "USERNAME": app_name,
        "APP_NAME": app_name,
        "MAIN_DOMAIN": app.get("main_domain", ""),
        "SERVER_NAMES": server_names,
        "SERVER_DOMAINS": domains,
        "PHP_SERVICE": php_service,
        "PHP_FRONT_CONTROLLER": php_entrypoint == "front-controller",
        "DOCUMENT_ROOT": container_document_root(app_name, public_dir),
    })
    apply_vhost_tls(conf_path, app)
    app["vhost"] = rel(conf_path)
    return conf_path
