"""Repository root, runtime path constants, and render destination context."""

from __future__ import annotations

import datetime as _dt
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONFIG_DIR = ROOT / "config"
RUNTIME_DIR = ROOT / "runtime"
STATE_DIR = RUNTIME_DIR / "state"
DB_PATH = STATE_DIR / "stack.json"
LEGACY_DB_PATH = ROOT / "stack.json"
GENERATED_DIR = RUNTIME_DIR / "generated"
CUSTOM_DIR = RUNTIME_DIR / "custom"
HOME_DIR = RUNTIME_DIR / "home"
PHP_CONFIG_DIR = CONFIG_DIR / "php"
PHP_GENERATED_DIR = GENERATED_DIR / "php"
PHP_VERSIONS_DIR = PHP_GENERATED_DIR / "versions"
LEGACY_PHP_VERSIONS_DIR = PHP_CONFIG_DIR / "versions"
PHP_TEMPLATE_DIR = PHP_CONFIG_DIR / "templates"
MYSQL_TEMPLATE_DIR = CONFIG_DIR / "mysql" / "templates"
MYSQL_SECRETS_DIR = RUNTIME_DIR / "secrets" / "mysql"
NGINX_TEMPLATE_DIR = CONFIG_DIR / "nginx" / "templates"
NGINX_VHOST_DIR = GENERATED_DIR / "nginx" / "vhosts"
CERTS_DIR = RUNTIME_DIR / "certs"
PHP_SOCKET_DIR = RUNTIME_DIR / "run" / "php-fpm"
PHP_LOG_DIR = RUNTIME_DIR / "logs" / "php"
CRON_RUNTIME_DIR = GENERATED_DIR / "cron"
SCHEMA_VERSION = 5
DOCROOT_NAME = "www"
GENERATED_NOTICE = "GENERATED BY VIBEOPS. Do not edit directly; update runtime/state/stack.json and run ./manage.py render."
GENERATED_HEADER = f"# {GENERATED_NOTICE}\n"
PHP_FPM_GENERATED_HEADER = f"; {GENERATED_NOTICE}\n"

# Managed relative paths under a generated root (used for stale cleanup).
GENERATED_MANAGED_GLOBS = (
    "nginx/vhosts/*.conf",
    "php/versions/*/users.d/*.env",
    "php/versions/*/pool.d/*.conf",
    "cron/php*/jobs/*.cron",
    "cron/php*/.supercronic.cron",
    "cron/php*/.logrotate.conf",
)

# Journal schema for render transactions (local, versioned).
RENDER_TXN_JOURNAL_VERSION = 1
RENDER_TXN_DIR_PREFIX = ".render-txn-"


@dataclass(frozen=True)
class RenderContext:
    """Destination roots for generated service config and MySQL option files.

    Live render uses ``runtime/generated`` and ``runtime/secrets/mysql``. Staging
    render points these at a temporary tree under the same filesystem so
    ``os.replace`` stays atomic during promotion.
    """

    generated_dir: Path
    secrets_dir: Path

    def nginx_vhost_dir(self) -> Path:
        return self.generated_dir / "nginx" / "vhosts"

    def php_versions_dir(self) -> Path:
        return self.generated_dir / "php" / "versions"

    def php_version_config_dir(self, version: str) -> Path:
        return self.php_versions_dir() / version

    def cron_runtime_dir(self) -> Path:
        return self.generated_dir / "cron"

    def cron_dir_for(self, version: str) -> Path:
        from vibeops.php import php_service_for

        return self.cron_runtime_dir() / php_service_for(version)

    def cron_jobs_dir_for(self, version: str) -> Path:
        return self.cron_dir_for(version) / "jobs"

    def app_vhost_path(self, app_name: str) -> Path:
        return self.nginx_vhost_dir() / f"app-{app_name}.conf"

    def proxy_vhost_path(self, domain: str) -> Path:
        return self.nginx_vhost_dir() / f"{domain}.conf"

    def mysql_root_option_file(self, service: str) -> Path:
        from vibeops.validation import MYSQL_SERVICE_RE, validate

        service = validate(service, MYSQL_SERVICE_RE, "MySQL service")
        return self.secrets_dir / f"{service}-root.cnf"


def live_render_context() -> RenderContext:
    return RenderContext(generated_dir=GENERATED_DIR, secrets_dir=MYSQL_SECRETS_DIR)


def now() -> str:
    return _dt.datetime.now(_dt.timezone.utc).replace(microsecond=0).isoformat()


def rel(path: Path | str) -> str:
    p = Path(path)
    try:
        return str(p.resolve().relative_to(ROOT))
    except Exception:
        return str(p)
