"""Managed MySQL versions and generated Docker Compose services."""
from __future__ import annotations

import platform
from pathlib import Path
from typing import Any

from bento.os.fsutil import mkdir, write_text_atomic
from bento.utils.errors import die
from bento.utils.paths import ROOT
from bento.utils.validation import MYSQL_VERSION_RE, validate

MYSQL_COMPOSE_PATH = ROOT / "compose.d" / "bento-mysql-versions.yml"
ARM64_ARCHITECTURES = frozenset({"aarch64", "arm64"})


def host_is_arm64(machine: str | None = None) -> bool:
    """Return whether Compose is being rendered on a 64-bit ARM host."""
    return (machine or platform.machine()).strip().lower() in ARM64_ARCHITECTURES


def mysql_service_for(version: str) -> str:
    return f"mysql{version.replace('.', '')}"


def managed_mysql_versions(db: dict[str, Any]) -> list[str]:
    raw = db.get("mysql_versions", ["8.4"])
    if not isinstance(raw, list):
        die("state mysql_versions must be a list")
    versions = {validate(str(item), MYSQL_VERSION_RE, "MySQL version") for item in raw}
    return sorted(versions, key=lambda value: tuple(int(part) for part in value.split(".")))


def render_mysql_versions_compose(
    db: dict[str, Any],
    path: Path = MYSQL_COMPOSE_PATH,
    *,
    machine: str | None = None,
) -> Path:
    """Render one durable MySQL service and named volume per managed version."""
    arm64 = host_is_arm64(machine)
    lines = [
        "# GENERATED BY bento. Manage with ./manage.py mysql versions\n",
        "x-bento-mysql-healthcheck: &bento-mysql-healthcheck\n",
        "  test: [\"CMD\", \"mysqladmin\", \"--defaults-extra-file=/run/secrets/bento-root.cnf\", \"ping\", \"--silent\"]\n",
        "  interval: 5s\n  timeout: 5s\n  retries: 20\n  start_period: 30s\n",
        "\nservices:\n",
    ]
    volumes: list[str] = []
    for version in managed_mysql_versions(db):
        service = mysql_service_for(version)
        compact = version.replace(".", "")
        default_pool = "384M" if version.startswith("5.") else "512M"
        version_config = ROOT / "config" / "mysql" / "versions" / version / "conf.d" / "90-version.cnf"
        version_mount = (
            f"      - ./config/mysql/versions/{version}/conf.d/90-version.cnf:/etc/mysql/conf.d/90-version.cnf:ro\n"
            if version_config.is_file() else ""
        )
        if version == "5.7" and arm64:
            image_source = (
                "    build:\n"
                "      context: ./docker/mysql/5.7\n"
                "      dockerfile: Dockerfile\n"
                "    image: bento/mysql:5.7-arm64\n"
            )
        else:
            image_source = (
                "    build:\n"
                "      context: ./docker/mysql\n"
                "      dockerfile: Dockerfile\n"
                "      args:\n"
                f"        MYSQL_BASE_IMAGE: mysql:${{MYSQL{compact}_VERSION:-{version}}}\n"
                f"    image: bento/mysql:${{MYSQL{compact}_VERSION:-{version}}}\n"
            )
        lines.extend([
            f"  {service}:\n",
            image_source,
            "    restart: unless-stopped\n",
            "    logging:\n      driver: local\n      options:\n        max-size: \"${DOCKER_LOG_MAX_SIZE:-20m}\"\n        max-file: \"${DOCKER_LOG_MAX_FILE:-5}\"\n",
            f"    command: [\"--innodb-buffer-pool-size=${{MYSQL_INNODB_BUFFER_POOL_SIZE:-{default_pool}}}\"]\n",
            "    environment:\n",
            f"      MYSQL_ROOT_PASSWORD: ${{MYSQL{compact}_ROOT_PASSWORD:-${{MYSQL_ROOT_PASSWORD:?set MYSQL_ROOT_PASSWORD in .env}}}}\n",
            "      TZ: ${TZ:-Asia/Ho_Chi_Minh}\n",
            "    volumes:\n",
            f"      - {service}-data:/var/lib/mysql\n",
            "      - ./config/mysql/common/conf.d/10-common.cnf:/etc/mysql/conf.d/10-common.cnf:ro\n",
            version_mount,
            f"      - ./runtime/backups/{service}:/backups\n",
            f"      - ./runtime/logs/{service}:/var/log/mysql\n",
            f"      - ./runtime/secrets/mysql/{service}-root.cnf:/run/secrets/bento-root.cnf:ro\n",
            "    healthcheck: *bento-mysql-healthcheck\n",
            "    networks: [backend]\n",
        ])
        volumes.append(service)
    lines.append("\nvolumes:\n")
    lines.extend(f"  {service}-data:\n" for service in volumes)
    mkdir(path.parent)
    write_text_atomic(path, "".join(lines))
    return path
