"""Managed PHP versions and generated Docker Compose services."""
from __future__ import annotations

from pathlib import Path
from typing import Any

from bento.os.fsutil import mkdir, write_text_atomic
from bento.services.php import php_service_for
from bento.utils.errors import die
from bento.utils.paths import ROOT
from bento.utils.validation import PHP_VERSION_RE, validate

PHP_COMPOSE_PATH = ROOT / "compose.d" / "bento-php-versions.yml"


def managed_php_versions(db: dict[str, Any]) -> list[str]:
    raw = db.get("php_versions", ["8.5"])
    if not isinstance(raw, list):
        die("state php_versions must be a list")
    versions = {validate(str(item), PHP_VERSION_RE, "PHP version") for item in raw}
    return sorted(versions)


def _service(version: str, role: str) -> str:
    base = php_service_for(version)
    return base if role == "fpm" else f"{base}-{role}"


def render_php_versions_compose(db: dict[str, Any], path: Path = PHP_COMPOSE_PATH) -> Path:
    """Render all managed FPM, runner, and ephemeral CLI services."""
    lines = [
        "# GENERATED BY bento. Manage with ./manage.py php versions\n",
        "x-common-php: &common-php\n",
        "  build:\n    context: ./docker/php\n",
        "  entrypoint: [\"docker-php-entrypoint\"]\n",
        "  environment:\n",
        "    TZ: ${TZ:-Asia/Ho_Chi_Minh}\n",
        "    SOCKET_GROUP_NAME: ${SOCKET_GROUP_NAME:-nginxsock}\n",
        "    SOCKET_GID: ${SOCKET_GID:-101}\n",
        "  networks: [backend]\n",
        "  logging:\n    driver: local\n    options:\n      max-size: \"${DOCKER_LOG_MAX_SIZE:-20m}\"\n      max-file: \"${DOCKER_LOG_MAX_FILE:-5}\"\n",
        "\nservices:\n",
    ]
    common_mounts = [
        "./runtime/home:/home",
        "./config/php/common/conf.d/90-custom.ini:/usr/local/etc/php/conf.d/90-custom.ini:ro",
        "./config/php/supervisor/supervisord.conf:/etc/bento/supervisord.conf:ro",
        "./docker/php/bin/php-identity-sync:/usr/local/bin/php-identity-sync:ro",
        "./docker/php/bin/php-permissions:/usr/local/bin/php-permissions:ro",
        "./docker/php/bin/php-app-run:/usr/local/bin/php-app-run:ro",
        "./docker/php/bin/php-cron-job:/usr/local/bin/php-cron-job:ro",
        "./docker/php/bin/php-supercronic:/usr/local/bin/php-supercronic:ro",
        "./docker/php/bin/bento-deploy-drain:/usr/local/bin/bento-deploy-drain:ro",
        "./docker/php/lib/bento:/usr/local/lib/bento:ro",
    ]
    for version in managed_php_versions(db):
        service = php_service_for(version)
        compact = version.replace(".", "")
        version_var = f"PHP{compact}_VERSION"
        mounts = [
            *common_mounts[:1],
            f"./runtime/run/php-fpm/{service}:/run/php-fpm",
            f"./runtime/logs/php/{service}:/var/log/php",
            *common_mounts[1:2],
            f"./runtime/generated/php/versions/{version}/pool.d:/usr/local/etc/php-fpm.d/pools:ro",
            f"./runtime/generated/php/versions/{version}/users.d:/usr/local/etc/php/users.d:ro",
            f"./runtime/generated/cron/{service}:/usr/local/etc/php/cron.d:ro",
            f"./runtime/generated/runner/{service}/programs:/etc/bento/programs:ro",
            *common_mounts[2:],
        ]
        shared = [
            "    <<: *common-php\n",
            f"    image: bento-{service}:${{{version_var}:-{version}}}\n",
            "    build:\n      context: ./docker/php\n      args:\n",
            f"        PHP_VERSION: ${{{version_var}:-{version}}}\n",
            "        PHP_FPM_PROCESS_MAX: ${PHP_FPM_PROCESS_MAX:-32}\n",
            "        TZ: ${TZ:-Asia/Ho_Chi_Minh}\n",
            "    volumes:\n",
            *[f"      - {mount}\n" for mount in mounts],
        ]
        lines.extend([f"  {service}:\n", *shared, "    restart: unless-stopped\n", "    command: [\"sh\", \"-lc\", \"php-identity-sync && exec php-fpm -F\"]\n"])
        lines.extend([f"  {_service(version, 'runner')}:\n", *shared, "    restart: unless-stopped\n", "    command: [\"sh\", \"-lc\", \"php-identity-sync && exec supervisord -n -c /etc/bento/supervisord.conf\"]\n"])
        lines.extend([f"  {_service(version, 'cli')}:\n", *shared, "    profiles: [\"cli\"]\n", "    entrypoint: [\"php-app-run\"]\n", "    command: [\"bash\"]\n"])
    mkdir(path.parent)
    write_text_atomic(path, "".join(lines))
    return path
