; bento-managed: true
[vb1]
user = 2000
group = 2000
listen = /run/php-fpm/vb1.sock
listen.owner = 2000
listen.group = 1500
listen.mode = 0660
pm = dynamic
pm.max_children = 10
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 5
php_admin_value[open_basedir] = /home/vb1:/usr/share/php:/tmp
php_admin_value[upload_tmp_dir] = /home/vb1/tmp
php_admin_value[session.save_path] = /home/vb1/tmp/sessions
slowlog = /home/vb1/logs/php-slow.log
request_slowlog_timeout = 5s
catch_workers_output = yes
